// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: github.com/gomatcha/matcha/proto/keyboard/keyboard.proto

package com.github.gomatcha.matcha.proto.keyboard;

public final class PbKeyboard {
  private PbKeyboard() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code matcha.keyboard.Type}
   */
  public enum Type
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>TEXT_TYPE = 0;</code>
     */
    TEXT_TYPE(0),
    /**
     * <code>NUMBER_TYPE = 1;</code>
     */
    NUMBER_TYPE(1),
    /**
     * <code>EMAIL_TYPE = 2;</code>
     */
    EMAIL_TYPE(2),
    /**
     * <code>URL_TYPE = 3;</code>
     */
    URL_TYPE(3),
    /**
     * <code>PHONE_TYPE = 4;</code>
     */
    PHONE_TYPE(4),
    /**
     * <code>DATE_TIME_TYPE = 5;</code>
     */
    DATE_TIME_TYPE(5),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>TEXT_TYPE = 0;</code>
     */
    public static final int TEXT_TYPE_VALUE = 0;
    /**
     * <code>NUMBER_TYPE = 1;</code>
     */
    public static final int NUMBER_TYPE_VALUE = 1;
    /**
     * <code>EMAIL_TYPE = 2;</code>
     */
    public static final int EMAIL_TYPE_VALUE = 2;
    /**
     * <code>URL_TYPE = 3;</code>
     */
    public static final int URL_TYPE_VALUE = 3;
    /**
     * <code>PHONE_TYPE = 4;</code>
     */
    public static final int PHONE_TYPE_VALUE = 4;
    /**
     * <code>DATE_TIME_TYPE = 5;</code>
     */
    public static final int DATE_TIME_TYPE_VALUE = 5;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Type valueOf(int value) {
      return forNumber(value);
    }

    public static Type forNumber(int value) {
      switch (value) {
        case 0: return TEXT_TYPE;
        case 1: return NUMBER_TYPE;
        case 2: return EMAIL_TYPE;
        case 3: return URL_TYPE;
        case 4: return PHONE_TYPE;
        case 5: return DATE_TIME_TYPE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Type>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Type> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Type>() {
            public Type findValueByNumber(int number) {
              return Type.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.github.gomatcha.matcha.proto.keyboard.PbKeyboard.getDescriptor().getEnumTypes().get(0);
    }

    private static final Type[] VALUES = values();

    public static Type valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Type(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:matcha.keyboard.Type)
  }

  /**
   * Protobuf enum {@code matcha.keyboard.Appearance}
   */
  public enum Appearance
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>DEFAULT_APPEARANCE = 0;</code>
     */
    DEFAULT_APPEARANCE(0),
    /**
     * <code>LIGHT_APPEARANCE = 1;</code>
     */
    LIGHT_APPEARANCE(1),
    /**
     * <code>DARK_APPEARANCE = 2;</code>
     */
    DARK_APPEARANCE(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>DEFAULT_APPEARANCE = 0;</code>
     */
    public static final int DEFAULT_APPEARANCE_VALUE = 0;
    /**
     * <code>LIGHT_APPEARANCE = 1;</code>
     */
    public static final int LIGHT_APPEARANCE_VALUE = 1;
    /**
     * <code>DARK_APPEARANCE = 2;</code>
     */
    public static final int DARK_APPEARANCE_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Appearance valueOf(int value) {
      return forNumber(value);
    }

    public static Appearance forNumber(int value) {
      switch (value) {
        case 0: return DEFAULT_APPEARANCE;
        case 1: return LIGHT_APPEARANCE;
        case 2: return DARK_APPEARANCE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Appearance>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Appearance> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Appearance>() {
            public Appearance findValueByNumber(int number) {
              return Appearance.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.github.gomatcha.matcha.proto.keyboard.PbKeyboard.getDescriptor().getEnumTypes().get(1);
    }

    private static final Appearance[] VALUES = values();

    public static Appearance valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Appearance(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:matcha.keyboard.Appearance)
  }

  /**
   * Protobuf enum {@code matcha.keyboard.ReturnType}
   */
  public enum ReturnType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>DEFAULT_RETURN_TYPE = 0;</code>
     */
    DEFAULT_RETURN_TYPE(0),
    /**
     * <code>GO_RETURN_TYPE = 1;</code>
     */
    GO_RETURN_TYPE(1),
    /**
     * <code>GOOGLE_RETURN_TYPE = 2;</code>
     */
    GOOGLE_RETURN_TYPE(2),
    /**
     * <code>JOIN_RETURN_TYPE = 3;</code>
     */
    JOIN_RETURN_TYPE(3),
    /**
     * <code>NEXT_RETURN_TYPE = 4;</code>
     */
    NEXT_RETURN_TYPE(4),
    /**
     * <code>ROUTE_RETURN_TYPE = 5;</code>
     */
    ROUTE_RETURN_TYPE(5),
    /**
     * <code>SEARCH_RETURN_TYPE = 6;</code>
     */
    SEARCH_RETURN_TYPE(6),
    /**
     * <code>SEND_RETURN_TYPE = 7;</code>
     */
    SEND_RETURN_TYPE(7),
    /**
     * <code>YAHOO_RETURN_TYPE = 8;</code>
     */
    YAHOO_RETURN_TYPE(8),
    /**
     * <code>DONE_RETURN_TYPE = 9;</code>
     */
    DONE_RETURN_TYPE(9),
    /**
     * <code>EMERGENCY_CALL_RETURN_TYPE = 10;</code>
     */
    EMERGENCY_CALL_RETURN_TYPE(10),
    /**
     * <code>CONTINUE_RETURN_TYPE = 11;</code>
     */
    CONTINUE_RETURN_TYPE(11),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>DEFAULT_RETURN_TYPE = 0;</code>
     */
    public static final int DEFAULT_RETURN_TYPE_VALUE = 0;
    /**
     * <code>GO_RETURN_TYPE = 1;</code>
     */
    public static final int GO_RETURN_TYPE_VALUE = 1;
    /**
     * <code>GOOGLE_RETURN_TYPE = 2;</code>
     */
    public static final int GOOGLE_RETURN_TYPE_VALUE = 2;
    /**
     * <code>JOIN_RETURN_TYPE = 3;</code>
     */
    public static final int JOIN_RETURN_TYPE_VALUE = 3;
    /**
     * <code>NEXT_RETURN_TYPE = 4;</code>
     */
    public static final int NEXT_RETURN_TYPE_VALUE = 4;
    /**
     * <code>ROUTE_RETURN_TYPE = 5;</code>
     */
    public static final int ROUTE_RETURN_TYPE_VALUE = 5;
    /**
     * <code>SEARCH_RETURN_TYPE = 6;</code>
     */
    public static final int SEARCH_RETURN_TYPE_VALUE = 6;
    /**
     * <code>SEND_RETURN_TYPE = 7;</code>
     */
    public static final int SEND_RETURN_TYPE_VALUE = 7;
    /**
     * <code>YAHOO_RETURN_TYPE = 8;</code>
     */
    public static final int YAHOO_RETURN_TYPE_VALUE = 8;
    /**
     * <code>DONE_RETURN_TYPE = 9;</code>
     */
    public static final int DONE_RETURN_TYPE_VALUE = 9;
    /**
     * <code>EMERGENCY_CALL_RETURN_TYPE = 10;</code>
     */
    public static final int EMERGENCY_CALL_RETURN_TYPE_VALUE = 10;
    /**
     * <code>CONTINUE_RETURN_TYPE = 11;</code>
     */
    public static final int CONTINUE_RETURN_TYPE_VALUE = 11;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ReturnType valueOf(int value) {
      return forNumber(value);
    }

    public static ReturnType forNumber(int value) {
      switch (value) {
        case 0: return DEFAULT_RETURN_TYPE;
        case 1: return GO_RETURN_TYPE;
        case 2: return GOOGLE_RETURN_TYPE;
        case 3: return JOIN_RETURN_TYPE;
        case 4: return NEXT_RETURN_TYPE;
        case 5: return ROUTE_RETURN_TYPE;
        case 6: return SEARCH_RETURN_TYPE;
        case 7: return SEND_RETURN_TYPE;
        case 8: return YAHOO_RETURN_TYPE;
        case 9: return DONE_RETURN_TYPE;
        case 10: return EMERGENCY_CALL_RETURN_TYPE;
        case 11: return CONTINUE_RETURN_TYPE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ReturnType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ReturnType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ReturnType>() {
            public ReturnType findValueByNumber(int number) {
              return ReturnType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.github.gomatcha.matcha.proto.keyboard.PbKeyboard.getDescriptor().getEnumTypes().get(2);
    }

    private static final ReturnType[] VALUES = values();

    public static ReturnType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ReturnType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:matcha.keyboard.ReturnType)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n8github.com/gomatcha/matcha/proto/keybo" +
      "ard/keyboard.proto\022\017matcha.keyboard*h\n\004T" +
      "ype\022\r\n\tTEXT_TYPE\020\000\022\017\n\013NUMBER_TYPE\020\001\022\016\n\nE" +
      "MAIL_TYPE\020\002\022\014\n\010URL_TYPE\020\003\022\016\n\nPHONE_TYPE\020" +
      "\004\022\022\n\016DATE_TIME_TYPE\020\005*O\n\nAppearance\022\026\n\022D" +
      "EFAULT_APPEARANCE\020\000\022\024\n\020LIGHT_APPEARANCE\020" +
      "\001\022\023\n\017DARK_APPEARANCE\020\002*\251\002\n\nReturnType\022\027\n" +
      "\023DEFAULT_RETURN_TYPE\020\000\022\022\n\016GO_RETURN_TYPE" +
      "\020\001\022\026\n\022GOOGLE_RETURN_TYPE\020\002\022\024\n\020JOIN_RETUR" +
      "N_TYPE\020\003\022\024\n\020NEXT_RETURN_TYPE\020\004\022\025\n\021ROUTE_" +
      "RETURN_TYPE\020\005\022\026\n\022SEARCH_RETURN_TYPE\020\006\022\024\n" +
      "\020SEND_RETURN_TYPE\020\007\022\025\n\021YAHOO_RETURN_TYPE" +
      "\020\010\022\024\n\020DONE_RETURN_TYPE\020\t\022\036\n\032EMERGENCY_CA" +
      "LL_RETURN_TYPE\020\n\022\030\n\024CONTINUE_RETURN_TYPE" +
      "\020\013BT\n)com.github.gomatcha.matcha.proto.k" +
      "eyboardB\nPbKeyboardZ\010keyboard\242\002\020MatchaKe" +
      "yboardPBb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
