// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gomatcha.io/matcha/pb/color.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "gomatcha.io/matcha/pb/Color.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - MatchaPBColorRoot

@implementation MatchaPBColorRoot

// No extensions in the file and no imports, so no need to generate
// +extensionRegistry.

@end

#pragma mark - MatchaPBColorRoot_FileDescriptor

static GPBFileDescriptor *MatchaPBColorRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"matcha"
                                                 objcPrefix:@"MatchaPB"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - MatchaPBColor

@implementation MatchaPBColor

@dynamic red;
@dynamic blue;
@dynamic green;
@dynamic alpha;

typedef struct MatchaPBColor__storage_ {
  uint32_t _has_storage_[1];
  uint32_t red;
  uint32_t blue;
  uint32_t green;
  uint32_t alpha;
} MatchaPBColor__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "red",
        .dataTypeSpecific.className = NULL,
        .number = MatchaPBColor_FieldNumber_Red,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(MatchaPBColor__storage_, red),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeUInt32,
      },
      {
        .name = "blue",
        .dataTypeSpecific.className = NULL,
        .number = MatchaPBColor_FieldNumber_Blue,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(MatchaPBColor__storage_, blue),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeUInt32,
      },
      {
        .name = "green",
        .dataTypeSpecific.className = NULL,
        .number = MatchaPBColor_FieldNumber_Green,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(MatchaPBColor__storage_, green),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeUInt32,
      },
      {
        .name = "alpha",
        .dataTypeSpecific.className = NULL,
        .number = MatchaPBColor_FieldNumber_Alpha,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(MatchaPBColor__storage_, alpha),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeUInt32,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[MatchaPBColor class]
                                     rootClass:[MatchaPBColorRoot class]
                                          file:MatchaPBColorRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(MatchaPBColor__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
