// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gomatcha.io/matcha/proto/view/android/pagerview.proto

/*
Package android is a generated protocol buffer package.

It is generated from these files:
	gomatcha.io/matcha/proto/view/android/pagerview.proto
	gomatcha.io/matcha/proto/view/android/stackview.proto
	gomatcha.io/matcha/proto/view/android/statusbar.proto

It has these top-level messages:
	PagerChildView
	PagerView
	PagerEvent
	StackChildView
	StackView
	StackBar
	StackBarItem
	StackEvent
	StatusBar
*/
package android

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PagerChildView struct {
	Title string `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
}

func (m *PagerChildView) Reset()                    { *m = PagerChildView{} }
func (m *PagerChildView) String() string            { return proto.CompactTextString(m) }
func (*PagerChildView) ProtoMessage()               {}
func (*PagerChildView) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PagerChildView) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type PagerView struct {
	ChildViews    []*PagerChildView `protobuf:"bytes,1,rep,name=childViews" json:"childViews,omitempty"`
	SelectedIndex int64             `protobuf:"varint,2,opt,name=selectedIndex" json:"selectedIndex,omitempty"`
}

func (m *PagerView) Reset()                    { *m = PagerView{} }
func (m *PagerView) String() string            { return proto.CompactTextString(m) }
func (*PagerView) ProtoMessage()               {}
func (*PagerView) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PagerView) GetChildViews() []*PagerChildView {
	if m != nil {
		return m.ChildViews
	}
	return nil
}

func (m *PagerView) GetSelectedIndex() int64 {
	if m != nil {
		return m.SelectedIndex
	}
	return 0
}

type PagerEvent struct {
	SelectedIndex int64 `protobuf:"varint,1,opt,name=selectedIndex" json:"selectedIndex,omitempty"`
}

func (m *PagerEvent) Reset()                    { *m = PagerEvent{} }
func (m *PagerEvent) String() string            { return proto.CompactTextString(m) }
func (*PagerEvent) ProtoMessage()               {}
func (*PagerEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PagerEvent) GetSelectedIndex() int64 {
	if m != nil {
		return m.SelectedIndex
	}
	return 0
}

func init() {
	proto.RegisterType((*PagerChildView)(nil), "matcha.view.android.PagerChildView")
	proto.RegisterType((*PagerView)(nil), "matcha.view.android.PagerView")
	proto.RegisterType((*PagerEvent)(nil), "matcha.view.android.PagerEvent")
}

func init() {
	proto.RegisterFile("gomatcha.io/matcha/proto/view/android/pagerview.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 225 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0x4d, 0xcf, 0xcf, 0x4d,
	0x2c, 0x49, 0xce, 0x48, 0xd4, 0xcb, 0xcc, 0xd7, 0x87, 0xb0, 0xf4, 0x0b, 0x8a, 0xf2, 0x4b, 0xf2,
	0xf5, 0xcb, 0x32, 0x53, 0xcb, 0xf5, 0x13, 0xf3, 0x52, 0x8a, 0xf2, 0x33, 0x53, 0xf4, 0x0b, 0x12,
	0xd3, 0x53, 0x8b, 0x40, 0x22, 0x7a, 0x60, 0x49, 0x21, 0x61, 0xa8, 0x26, 0xb0, 0x10, 0x54, 0x91,
	0x92, 0x1a, 0x17, 0x5f, 0x00, 0x48, 0x9d, 0x73, 0x46, 0x66, 0x4e, 0x4a, 0x58, 0x66, 0x6a, 0xb9,
	0x90, 0x08, 0x17, 0x6b, 0x49, 0x66, 0x49, 0x4e, 0xaa, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x67, 0x10,
	0x84, 0xa3, 0x54, 0xc6, 0xc5, 0x09, 0x56, 0x07, 0x56, 0xe2, 0xcc, 0xc5, 0x95, 0x0c, 0x53, 0x5f,
	0x2c, 0xc1, 0xa8, 0xc0, 0xac, 0xc1, 0x6d, 0xa4, 0xac, 0x87, 0xc5, 0x78, 0x3d, 0x54, 0xb3, 0x83,
	0x90, 0xb4, 0x09, 0xa9, 0x70, 0xf1, 0x16, 0xa7, 0xe6, 0xa4, 0x26, 0x97, 0xa4, 0xa6, 0x78, 0xe6,
	0xa5, 0xa4, 0x56, 0x80, 0xed, 0x63, 0x0e, 0x42, 0x15, 0x54, 0x32, 0xe2, 0xe2, 0x02, 0x9b, 0xe1,
	0x5a, 0x96, 0x9a, 0x57, 0x82, 0xa9, 0x87, 0x11, 0x8b, 0x1e, 0x27, 0x7f, 0x2e, 0xd5, 0xcc, 0x7c,
	0x3d, 0x78, 0x20, 0x41, 0x29, 0x70, 0x20, 0xa0, 0xb8, 0xce, 0x89, 0x3b, 0x20, 0x09, 0xee, 0xa9,
	0x28, 0x76, 0xa8, 0xe8, 0x22, 0x26, 0x7e, 0x5f, 0xb0, 0x0e, 0x47, 0x08, 0x3f, 0xc0, 0x29, 0x89,
	0x0d, 0xac, 0xd7, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x7d, 0x71, 0xf5, 0xb1, 0x79, 0x01, 0x00,
	0x00,
}
