// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/gomatcha/matcha/proto/view/android/pagerview.proto

package android

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PagerChildView struct {
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PagerChildView) Reset()         { *m = PagerChildView{} }
func (m *PagerChildView) String() string { return proto.CompactTextString(m) }
func (*PagerChildView) ProtoMessage()    {}
func (*PagerChildView) Descriptor() ([]byte, []int) {
	return fileDescriptor_48f3e48dfbbcc5d3, []int{0}
}
func (m *PagerChildView) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PagerChildView.Unmarshal(m, b)
}
func (m *PagerChildView) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PagerChildView.Marshal(b, m, deterministic)
}
func (m *PagerChildView) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PagerChildView.Merge(m, src)
}
func (m *PagerChildView) XXX_Size() int {
	return xxx_messageInfo_PagerChildView.Size(m)
}
func (m *PagerChildView) XXX_DiscardUnknown() {
	xxx_messageInfo_PagerChildView.DiscardUnknown(m)
}

var xxx_messageInfo_PagerChildView proto.InternalMessageInfo

func (m *PagerChildView) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type PagerView struct {
	ChildViews           []*PagerChildView `protobuf:"bytes,1,rep,name=childViews,proto3" json:"childViews,omitempty"`
	SelectedIndex        int64             `protobuf:"varint,2,opt,name=selectedIndex,proto3" json:"selectedIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PagerView) Reset()         { *m = PagerView{} }
func (m *PagerView) String() string { return proto.CompactTextString(m) }
func (*PagerView) ProtoMessage()    {}
func (*PagerView) Descriptor() ([]byte, []int) {
	return fileDescriptor_48f3e48dfbbcc5d3, []int{1}
}
func (m *PagerView) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PagerView.Unmarshal(m, b)
}
func (m *PagerView) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PagerView.Marshal(b, m, deterministic)
}
func (m *PagerView) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PagerView.Merge(m, src)
}
func (m *PagerView) XXX_Size() int {
	return xxx_messageInfo_PagerView.Size(m)
}
func (m *PagerView) XXX_DiscardUnknown() {
	xxx_messageInfo_PagerView.DiscardUnknown(m)
}

var xxx_messageInfo_PagerView proto.InternalMessageInfo

func (m *PagerView) GetChildViews() []*PagerChildView {
	if m != nil {
		return m.ChildViews
	}
	return nil
}

func (m *PagerView) GetSelectedIndex() int64 {
	if m != nil {
		return m.SelectedIndex
	}
	return 0
}

type PagerEvent struct {
	SelectedIndex        int64    `protobuf:"varint,1,opt,name=selectedIndex,proto3" json:"selectedIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PagerEvent) Reset()         { *m = PagerEvent{} }
func (m *PagerEvent) String() string { return proto.CompactTextString(m) }
func (*PagerEvent) ProtoMessage()    {}
func (*PagerEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_48f3e48dfbbcc5d3, []int{2}
}
func (m *PagerEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PagerEvent.Unmarshal(m, b)
}
func (m *PagerEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PagerEvent.Marshal(b, m, deterministic)
}
func (m *PagerEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PagerEvent.Merge(m, src)
}
func (m *PagerEvent) XXX_Size() int {
	return xxx_messageInfo_PagerEvent.Size(m)
}
func (m *PagerEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_PagerEvent.DiscardUnknown(m)
}

var xxx_messageInfo_PagerEvent proto.InternalMessageInfo

func (m *PagerEvent) GetSelectedIndex() int64 {
	if m != nil {
		return m.SelectedIndex
	}
	return 0
}

func init() {
	proto.RegisterType((*PagerChildView)(nil), "matcha.view.android.PagerChildView")
	proto.RegisterType((*PagerView)(nil), "matcha.view.android.PagerView")
	proto.RegisterType((*PagerEvent)(nil), "matcha.view.android.PagerEvent")
}

func init() {
	proto.RegisterFile("github.com/gomatcha/matcha/proto/view/android/pagerview.proto", fileDescriptor_48f3e48dfbbcc5d3)
}

var fileDescriptor_48f3e48dfbbcc5d3 = []byte{
	// 237 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xb2, 0x4d, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0x4f, 0xcf, 0xcf, 0x4d, 0x2c, 0x49, 0xce, 0x48, 0xd4,
	0x87, 0x52, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0xfa, 0x65, 0x99, 0xa9, 0xe5, 0xfa, 0x89, 0x79, 0x29,
	0x45, 0xf9, 0x99, 0x29, 0xfa, 0x05, 0x89, 0xe9, 0xa9, 0x45, 0x20, 0x11, 0x3d, 0xb0, 0xa4, 0x90,
	0x30, 0x44, 0xa9, 0x1e, 0x58, 0x08, 0xaa, 0x48, 0x49, 0x8d, 0x8b, 0x2f, 0x00, 0xa4, 0xce, 0x39,
	0x23, 0x33, 0x27, 0x25, 0x2c, 0x33, 0xb5, 0x5c, 0x48, 0x84, 0x8b, 0xb5, 0x24, 0xb3, 0x24, 0x27,
	0x55, 0x82, 0x49, 0x81, 0x51, 0x83, 0x33, 0x08, 0xc2, 0x51, 0x2a, 0xe3, 0xe2, 0x04, 0xab, 0x03,
	0x2b, 0x71, 0xe6, 0xe2, 0x4a, 0x86, 0xa9, 0x2f, 0x96, 0x60, 0x54, 0x60, 0xd6, 0xe0, 0x36, 0x52,
	0xd6, 0xc3, 0x62, 0xbc, 0x1e, 0xaa, 0xd9, 0x41, 0x48, 0xda, 0x84, 0x54, 0xb8, 0x78, 0x8b, 0x53,
	0x73, 0x52, 0x93, 0x4b, 0x52, 0x53, 0x3c, 0xf3, 0x52, 0x52, 0x2b, 0xc0, 0xf6, 0x31, 0x07, 0xa1,
	0x0a, 0x2a, 0x19, 0x71, 0x71, 0x81, 0xcd, 0x70, 0x2d, 0x4b, 0xcd, 0x2b, 0xc1, 0xd4, 0xc3, 0x88,
	0x45, 0x8f, 0x53, 0x38, 0x97, 0x6e, 0x72, 0x7e, 0xae, 0x1e, 0x34, 0xb4, 0x60, 0x21, 0x05, 0x73,
	0x1f, 0x38, 0x30, 0x50, 0x5c, 0xe9, 0xc4, 0x1d, 0x90, 0x04, 0xf7, 0x5c, 0x14, 0x3b, 0x54, 0x74,
	0x11, 0x13, 0xbf, 0x2f, 0x58, 0x87, 0x23, 0x84, 0x1f, 0xe0, 0x94, 0xc4, 0x06, 0xd6, 0x6b, 0x0c,
	0x08, 0x00, 0x00, 0xff, 0xff, 0xe5, 0xfd, 0xa7, 0x82, 0x89, 0x01, 0x00, 0x00,
}
