// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gomatcha.io/matcha/pb/layout/layout.proto

package io.gomatcha.matcha.pb.layout;

public final class PbLayout {
  private PbLayout() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PointOrBuilder extends
      // @@protoc_insertion_point(interface_extends:matcha.layout.Point)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>double x = 1;</code>
     */
    double getX();

    /**
     * <code>double y = 2;</code>
     */
    double getY();
  }
  /**
   * Protobuf type {@code matcha.layout.Point}
   */
  public  static final class Point extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:matcha.layout.Point)
      PointOrBuilder {
    // Use Point.newBuilder() to construct.
    private Point(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Point() {
      x_ = 0D;
      y_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Point(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 9: {

              x_ = input.readDouble();
              break;
            }
            case 17: {

              y_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.gomatcha.matcha.pb.layout.PbLayout.internal_static_matcha_layout_Point_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.gomatcha.matcha.pb.layout.PbLayout.internal_static_matcha_layout_Point_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.gomatcha.matcha.pb.layout.PbLayout.Point.class, io.gomatcha.matcha.pb.layout.PbLayout.Point.Builder.class);
    }

    public static final int X_FIELD_NUMBER = 1;
    private double x_;
    /**
     * <code>double x = 1;</code>
     */
    public double getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 2;
    private double y_;
    /**
     * <code>double y = 2;</code>
     */
    public double getY() {
      return y_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (x_ != 0D) {
        output.writeDouble(1, x_);
      }
      if (y_ != 0D) {
        output.writeDouble(2, y_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (x_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, x_);
      }
      if (y_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, y_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.gomatcha.matcha.pb.layout.PbLayout.Point)) {
        return super.equals(obj);
      }
      io.gomatcha.matcha.pb.layout.PbLayout.Point other = (io.gomatcha.matcha.pb.layout.PbLayout.Point) obj;

      boolean result = true;
      result = result && (
          java.lang.Double.doubleToLongBits(getX())
          == java.lang.Double.doubleToLongBits(
              other.getX()));
      result = result && (
          java.lang.Double.doubleToLongBits(getY())
          == java.lang.Double.doubleToLongBits(
              other.getY()));
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + X_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getX()));
      hash = (37 * hash) + Y_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getY()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.gomatcha.matcha.pb.layout.PbLayout.Point parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.gomatcha.matcha.pb.layout.PbLayout.Point parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.gomatcha.matcha.pb.layout.PbLayout.Point parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.gomatcha.matcha.pb.layout.PbLayout.Point parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.gomatcha.matcha.pb.layout.PbLayout.Point parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.gomatcha.matcha.pb.layout.PbLayout.Point parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.gomatcha.matcha.pb.layout.PbLayout.Point parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.gomatcha.matcha.pb.layout.PbLayout.Point parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.gomatcha.matcha.pb.layout.PbLayout.Point parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.gomatcha.matcha.pb.layout.PbLayout.Point parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.gomatcha.matcha.pb.layout.PbLayout.Point parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.gomatcha.matcha.pb.layout.PbLayout.Point parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.gomatcha.matcha.pb.layout.PbLayout.Point prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code matcha.layout.Point}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:matcha.layout.Point)
        io.gomatcha.matcha.pb.layout.PbLayout.PointOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.gomatcha.matcha.pb.layout.PbLayout.internal_static_matcha_layout_Point_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.gomatcha.matcha.pb.layout.PbLayout.internal_static_matcha_layout_Point_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.gomatcha.matcha.pb.layout.PbLayout.Point.class, io.gomatcha.matcha.pb.layout.PbLayout.Point.Builder.class);
      }

      // Construct using io.gomatcha.matcha.pb.layout.PbLayout.Point.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        x_ = 0D;

        y_ = 0D;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.gomatcha.matcha.pb.layout.PbLayout.internal_static_matcha_layout_Point_descriptor;
      }

      public io.gomatcha.matcha.pb.layout.PbLayout.Point getDefaultInstanceForType() {
        return io.gomatcha.matcha.pb.layout.PbLayout.Point.getDefaultInstance();
      }

      public io.gomatcha.matcha.pb.layout.PbLayout.Point build() {
        io.gomatcha.matcha.pb.layout.PbLayout.Point result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.gomatcha.matcha.pb.layout.PbLayout.Point buildPartial() {
        io.gomatcha.matcha.pb.layout.PbLayout.Point result = new io.gomatcha.matcha.pb.layout.PbLayout.Point(this);
        result.x_ = x_;
        result.y_ = y_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.gomatcha.matcha.pb.layout.PbLayout.Point) {
          return mergeFrom((io.gomatcha.matcha.pb.layout.PbLayout.Point)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.gomatcha.matcha.pb.layout.PbLayout.Point other) {
        if (other == io.gomatcha.matcha.pb.layout.PbLayout.Point.getDefaultInstance()) return this;
        if (other.getX() != 0D) {
          setX(other.getX());
        }
        if (other.getY() != 0D) {
          setY(other.getY());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.gomatcha.matcha.pb.layout.PbLayout.Point parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.gomatcha.matcha.pb.layout.PbLayout.Point) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private double x_ ;
      /**
       * <code>double x = 1;</code>
       */
      public double getX() {
        return x_;
      }
      /**
       * <code>double x = 1;</code>
       */
      public Builder setX(double value) {
        
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double x = 1;</code>
       */
      public Builder clearX() {
        
        x_ = 0D;
        onChanged();
        return this;
      }

      private double y_ ;
      /**
       * <code>double y = 2;</code>
       */
      public double getY() {
        return y_;
      }
      /**
       * <code>double y = 2;</code>
       */
      public Builder setY(double value) {
        
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double y = 2;</code>
       */
      public Builder clearY() {
        
        y_ = 0D;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:matcha.layout.Point)
    }

    // @@protoc_insertion_point(class_scope:matcha.layout.Point)
    private static final io.gomatcha.matcha.pb.layout.PbLayout.Point DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.gomatcha.matcha.pb.layout.PbLayout.Point();
    }

    public static io.gomatcha.matcha.pb.layout.PbLayout.Point getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Point>
        PARSER = new com.google.protobuf.AbstractParser<Point>() {
      public Point parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Point(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Point> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Point> getParserForType() {
      return PARSER;
    }

    public io.gomatcha.matcha.pb.layout.PbLayout.Point getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RectOrBuilder extends
      // @@protoc_insertion_point(interface_extends:matcha.layout.Rect)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.matcha.layout.Point min = 1;</code>
     */
    boolean hasMin();
    /**
     * <code>.matcha.layout.Point min = 1;</code>
     */
    io.gomatcha.matcha.pb.layout.PbLayout.Point getMin();
    /**
     * <code>.matcha.layout.Point min = 1;</code>
     */
    io.gomatcha.matcha.pb.layout.PbLayout.PointOrBuilder getMinOrBuilder();

    /**
     * <code>.matcha.layout.Point max = 2;</code>
     */
    boolean hasMax();
    /**
     * <code>.matcha.layout.Point max = 2;</code>
     */
    io.gomatcha.matcha.pb.layout.PbLayout.Point getMax();
    /**
     * <code>.matcha.layout.Point max = 2;</code>
     */
    io.gomatcha.matcha.pb.layout.PbLayout.PointOrBuilder getMaxOrBuilder();
  }
  /**
   * Protobuf type {@code matcha.layout.Rect}
   */
  public  static final class Rect extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:matcha.layout.Rect)
      RectOrBuilder {
    // Use Rect.newBuilder() to construct.
    private Rect(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Rect() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Rect(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              io.gomatcha.matcha.pb.layout.PbLayout.Point.Builder subBuilder = null;
              if (min_ != null) {
                subBuilder = min_.toBuilder();
              }
              min_ = input.readMessage(io.gomatcha.matcha.pb.layout.PbLayout.Point.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(min_);
                min_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              io.gomatcha.matcha.pb.layout.PbLayout.Point.Builder subBuilder = null;
              if (max_ != null) {
                subBuilder = max_.toBuilder();
              }
              max_ = input.readMessage(io.gomatcha.matcha.pb.layout.PbLayout.Point.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(max_);
                max_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.gomatcha.matcha.pb.layout.PbLayout.internal_static_matcha_layout_Rect_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.gomatcha.matcha.pb.layout.PbLayout.internal_static_matcha_layout_Rect_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.gomatcha.matcha.pb.layout.PbLayout.Rect.class, io.gomatcha.matcha.pb.layout.PbLayout.Rect.Builder.class);
    }

    public static final int MIN_FIELD_NUMBER = 1;
    private io.gomatcha.matcha.pb.layout.PbLayout.Point min_;
    /**
     * <code>.matcha.layout.Point min = 1;</code>
     */
    public boolean hasMin() {
      return min_ != null;
    }
    /**
     * <code>.matcha.layout.Point min = 1;</code>
     */
    public io.gomatcha.matcha.pb.layout.PbLayout.Point getMin() {
      return min_ == null ? io.gomatcha.matcha.pb.layout.PbLayout.Point.getDefaultInstance() : min_;
    }
    /**
     * <code>.matcha.layout.Point min = 1;</code>
     */
    public io.gomatcha.matcha.pb.layout.PbLayout.PointOrBuilder getMinOrBuilder() {
      return getMin();
    }

    public static final int MAX_FIELD_NUMBER = 2;
    private io.gomatcha.matcha.pb.layout.PbLayout.Point max_;
    /**
     * <code>.matcha.layout.Point max = 2;</code>
     */
    public boolean hasMax() {
      return max_ != null;
    }
    /**
     * <code>.matcha.layout.Point max = 2;</code>
     */
    public io.gomatcha.matcha.pb.layout.PbLayout.Point getMax() {
      return max_ == null ? io.gomatcha.matcha.pb.layout.PbLayout.Point.getDefaultInstance() : max_;
    }
    /**
     * <code>.matcha.layout.Point max = 2;</code>
     */
    public io.gomatcha.matcha.pb.layout.PbLayout.PointOrBuilder getMaxOrBuilder() {
      return getMax();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (min_ != null) {
        output.writeMessage(1, getMin());
      }
      if (max_ != null) {
        output.writeMessage(2, getMax());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (min_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getMin());
      }
      if (max_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getMax());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.gomatcha.matcha.pb.layout.PbLayout.Rect)) {
        return super.equals(obj);
      }
      io.gomatcha.matcha.pb.layout.PbLayout.Rect other = (io.gomatcha.matcha.pb.layout.PbLayout.Rect) obj;

      boolean result = true;
      result = result && (hasMin() == other.hasMin());
      if (hasMin()) {
        result = result && getMin()
            .equals(other.getMin());
      }
      result = result && (hasMax() == other.hasMax());
      if (hasMax()) {
        result = result && getMax()
            .equals(other.getMax());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMin()) {
        hash = (37 * hash) + MIN_FIELD_NUMBER;
        hash = (53 * hash) + getMin().hashCode();
      }
      if (hasMax()) {
        hash = (37 * hash) + MAX_FIELD_NUMBER;
        hash = (53 * hash) + getMax().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.gomatcha.matcha.pb.layout.PbLayout.Rect parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.gomatcha.matcha.pb.layout.PbLayout.Rect parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.gomatcha.matcha.pb.layout.PbLayout.Rect parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.gomatcha.matcha.pb.layout.PbLayout.Rect parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.gomatcha.matcha.pb.layout.PbLayout.Rect parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.gomatcha.matcha.pb.layout.PbLayout.Rect parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.gomatcha.matcha.pb.layout.PbLayout.Rect parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.gomatcha.matcha.pb.layout.PbLayout.Rect parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.gomatcha.matcha.pb.layout.PbLayout.Rect parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.gomatcha.matcha.pb.layout.PbLayout.Rect parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.gomatcha.matcha.pb.layout.PbLayout.Rect parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.gomatcha.matcha.pb.layout.PbLayout.Rect parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.gomatcha.matcha.pb.layout.PbLayout.Rect prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code matcha.layout.Rect}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:matcha.layout.Rect)
        io.gomatcha.matcha.pb.layout.PbLayout.RectOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.gomatcha.matcha.pb.layout.PbLayout.internal_static_matcha_layout_Rect_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.gomatcha.matcha.pb.layout.PbLayout.internal_static_matcha_layout_Rect_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.gomatcha.matcha.pb.layout.PbLayout.Rect.class, io.gomatcha.matcha.pb.layout.PbLayout.Rect.Builder.class);
      }

      // Construct using io.gomatcha.matcha.pb.layout.PbLayout.Rect.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (minBuilder_ == null) {
          min_ = null;
        } else {
          min_ = null;
          minBuilder_ = null;
        }
        if (maxBuilder_ == null) {
          max_ = null;
        } else {
          max_ = null;
          maxBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.gomatcha.matcha.pb.layout.PbLayout.internal_static_matcha_layout_Rect_descriptor;
      }

      public io.gomatcha.matcha.pb.layout.PbLayout.Rect getDefaultInstanceForType() {
        return io.gomatcha.matcha.pb.layout.PbLayout.Rect.getDefaultInstance();
      }

      public io.gomatcha.matcha.pb.layout.PbLayout.Rect build() {
        io.gomatcha.matcha.pb.layout.PbLayout.Rect result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.gomatcha.matcha.pb.layout.PbLayout.Rect buildPartial() {
        io.gomatcha.matcha.pb.layout.PbLayout.Rect result = new io.gomatcha.matcha.pb.layout.PbLayout.Rect(this);
        if (minBuilder_ == null) {
          result.min_ = min_;
        } else {
          result.min_ = minBuilder_.build();
        }
        if (maxBuilder_ == null) {
          result.max_ = max_;
        } else {
          result.max_ = maxBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.gomatcha.matcha.pb.layout.PbLayout.Rect) {
          return mergeFrom((io.gomatcha.matcha.pb.layout.PbLayout.Rect)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.gomatcha.matcha.pb.layout.PbLayout.Rect other) {
        if (other == io.gomatcha.matcha.pb.layout.PbLayout.Rect.getDefaultInstance()) return this;
        if (other.hasMin()) {
          mergeMin(other.getMin());
        }
        if (other.hasMax()) {
          mergeMax(other.getMax());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.gomatcha.matcha.pb.layout.PbLayout.Rect parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.gomatcha.matcha.pb.layout.PbLayout.Rect) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private io.gomatcha.matcha.pb.layout.PbLayout.Point min_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          io.gomatcha.matcha.pb.layout.PbLayout.Point, io.gomatcha.matcha.pb.layout.PbLayout.Point.Builder, io.gomatcha.matcha.pb.layout.PbLayout.PointOrBuilder> minBuilder_;
      /**
       * <code>.matcha.layout.Point min = 1;</code>
       */
      public boolean hasMin() {
        return minBuilder_ != null || min_ != null;
      }
      /**
       * <code>.matcha.layout.Point min = 1;</code>
       */
      public io.gomatcha.matcha.pb.layout.PbLayout.Point getMin() {
        if (minBuilder_ == null) {
          return min_ == null ? io.gomatcha.matcha.pb.layout.PbLayout.Point.getDefaultInstance() : min_;
        } else {
          return minBuilder_.getMessage();
        }
      }
      /**
       * <code>.matcha.layout.Point min = 1;</code>
       */
      public Builder setMin(io.gomatcha.matcha.pb.layout.PbLayout.Point value) {
        if (minBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          min_ = value;
          onChanged();
        } else {
          minBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.matcha.layout.Point min = 1;</code>
       */
      public Builder setMin(
          io.gomatcha.matcha.pb.layout.PbLayout.Point.Builder builderForValue) {
        if (minBuilder_ == null) {
          min_ = builderForValue.build();
          onChanged();
        } else {
          minBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.matcha.layout.Point min = 1;</code>
       */
      public Builder mergeMin(io.gomatcha.matcha.pb.layout.PbLayout.Point value) {
        if (minBuilder_ == null) {
          if (min_ != null) {
            min_ =
              io.gomatcha.matcha.pb.layout.PbLayout.Point.newBuilder(min_).mergeFrom(value).buildPartial();
          } else {
            min_ = value;
          }
          onChanged();
        } else {
          minBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.matcha.layout.Point min = 1;</code>
       */
      public Builder clearMin() {
        if (minBuilder_ == null) {
          min_ = null;
          onChanged();
        } else {
          min_ = null;
          minBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.matcha.layout.Point min = 1;</code>
       */
      public io.gomatcha.matcha.pb.layout.PbLayout.Point.Builder getMinBuilder() {
        
        onChanged();
        return getMinFieldBuilder().getBuilder();
      }
      /**
       * <code>.matcha.layout.Point min = 1;</code>
       */
      public io.gomatcha.matcha.pb.layout.PbLayout.PointOrBuilder getMinOrBuilder() {
        if (minBuilder_ != null) {
          return minBuilder_.getMessageOrBuilder();
        } else {
          return min_ == null ?
              io.gomatcha.matcha.pb.layout.PbLayout.Point.getDefaultInstance() : min_;
        }
      }
      /**
       * <code>.matcha.layout.Point min = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          io.gomatcha.matcha.pb.layout.PbLayout.Point, io.gomatcha.matcha.pb.layout.PbLayout.Point.Builder, io.gomatcha.matcha.pb.layout.PbLayout.PointOrBuilder> 
          getMinFieldBuilder() {
        if (minBuilder_ == null) {
          minBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              io.gomatcha.matcha.pb.layout.PbLayout.Point, io.gomatcha.matcha.pb.layout.PbLayout.Point.Builder, io.gomatcha.matcha.pb.layout.PbLayout.PointOrBuilder>(
                  getMin(),
                  getParentForChildren(),
                  isClean());
          min_ = null;
        }
        return minBuilder_;
      }

      private io.gomatcha.matcha.pb.layout.PbLayout.Point max_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          io.gomatcha.matcha.pb.layout.PbLayout.Point, io.gomatcha.matcha.pb.layout.PbLayout.Point.Builder, io.gomatcha.matcha.pb.layout.PbLayout.PointOrBuilder> maxBuilder_;
      /**
       * <code>.matcha.layout.Point max = 2;</code>
       */
      public boolean hasMax() {
        return maxBuilder_ != null || max_ != null;
      }
      /**
       * <code>.matcha.layout.Point max = 2;</code>
       */
      public io.gomatcha.matcha.pb.layout.PbLayout.Point getMax() {
        if (maxBuilder_ == null) {
          return max_ == null ? io.gomatcha.matcha.pb.layout.PbLayout.Point.getDefaultInstance() : max_;
        } else {
          return maxBuilder_.getMessage();
        }
      }
      /**
       * <code>.matcha.layout.Point max = 2;</code>
       */
      public Builder setMax(io.gomatcha.matcha.pb.layout.PbLayout.Point value) {
        if (maxBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          max_ = value;
          onChanged();
        } else {
          maxBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.matcha.layout.Point max = 2;</code>
       */
      public Builder setMax(
          io.gomatcha.matcha.pb.layout.PbLayout.Point.Builder builderForValue) {
        if (maxBuilder_ == null) {
          max_ = builderForValue.build();
          onChanged();
        } else {
          maxBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.matcha.layout.Point max = 2;</code>
       */
      public Builder mergeMax(io.gomatcha.matcha.pb.layout.PbLayout.Point value) {
        if (maxBuilder_ == null) {
          if (max_ != null) {
            max_ =
              io.gomatcha.matcha.pb.layout.PbLayout.Point.newBuilder(max_).mergeFrom(value).buildPartial();
          } else {
            max_ = value;
          }
          onChanged();
        } else {
          maxBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.matcha.layout.Point max = 2;</code>
       */
      public Builder clearMax() {
        if (maxBuilder_ == null) {
          max_ = null;
          onChanged();
        } else {
          max_ = null;
          maxBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.matcha.layout.Point max = 2;</code>
       */
      public io.gomatcha.matcha.pb.layout.PbLayout.Point.Builder getMaxBuilder() {
        
        onChanged();
        return getMaxFieldBuilder().getBuilder();
      }
      /**
       * <code>.matcha.layout.Point max = 2;</code>
       */
      public io.gomatcha.matcha.pb.layout.PbLayout.PointOrBuilder getMaxOrBuilder() {
        if (maxBuilder_ != null) {
          return maxBuilder_.getMessageOrBuilder();
        } else {
          return max_ == null ?
              io.gomatcha.matcha.pb.layout.PbLayout.Point.getDefaultInstance() : max_;
        }
      }
      /**
       * <code>.matcha.layout.Point max = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          io.gomatcha.matcha.pb.layout.PbLayout.Point, io.gomatcha.matcha.pb.layout.PbLayout.Point.Builder, io.gomatcha.matcha.pb.layout.PbLayout.PointOrBuilder> 
          getMaxFieldBuilder() {
        if (maxBuilder_ == null) {
          maxBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              io.gomatcha.matcha.pb.layout.PbLayout.Point, io.gomatcha.matcha.pb.layout.PbLayout.Point.Builder, io.gomatcha.matcha.pb.layout.PbLayout.PointOrBuilder>(
                  getMax(),
                  getParentForChildren(),
                  isClean());
          max_ = null;
        }
        return maxBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:matcha.layout.Rect)
    }

    // @@protoc_insertion_point(class_scope:matcha.layout.Rect)
    private static final io.gomatcha.matcha.pb.layout.PbLayout.Rect DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.gomatcha.matcha.pb.layout.PbLayout.Rect();
    }

    public static io.gomatcha.matcha.pb.layout.PbLayout.Rect getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Rect>
        PARSER = new com.google.protobuf.AbstractParser<Rect>() {
      public Rect parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Rect(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Rect> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Rect> getParserForType() {
      return PARSER;
    }

    public io.gomatcha.matcha.pb.layout.PbLayout.Rect getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface InsetsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:matcha.layout.Insets)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>double top = 1;</code>
     */
    double getTop();

    /**
     * <code>double left = 2;</code>
     */
    double getLeft();

    /**
     * <code>double bottom = 3;</code>
     */
    double getBottom();

    /**
     * <code>double right = 4;</code>
     */
    double getRight();
  }
  /**
   * Protobuf type {@code matcha.layout.Insets}
   */
  public  static final class Insets extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:matcha.layout.Insets)
      InsetsOrBuilder {
    // Use Insets.newBuilder() to construct.
    private Insets(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Insets() {
      top_ = 0D;
      left_ = 0D;
      bottom_ = 0D;
      right_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Insets(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 9: {

              top_ = input.readDouble();
              break;
            }
            case 17: {

              left_ = input.readDouble();
              break;
            }
            case 25: {

              bottom_ = input.readDouble();
              break;
            }
            case 33: {

              right_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.gomatcha.matcha.pb.layout.PbLayout.internal_static_matcha_layout_Insets_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.gomatcha.matcha.pb.layout.PbLayout.internal_static_matcha_layout_Insets_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.gomatcha.matcha.pb.layout.PbLayout.Insets.class, io.gomatcha.matcha.pb.layout.PbLayout.Insets.Builder.class);
    }

    public static final int TOP_FIELD_NUMBER = 1;
    private double top_;
    /**
     * <code>double top = 1;</code>
     */
    public double getTop() {
      return top_;
    }

    public static final int LEFT_FIELD_NUMBER = 2;
    private double left_;
    /**
     * <code>double left = 2;</code>
     */
    public double getLeft() {
      return left_;
    }

    public static final int BOTTOM_FIELD_NUMBER = 3;
    private double bottom_;
    /**
     * <code>double bottom = 3;</code>
     */
    public double getBottom() {
      return bottom_;
    }

    public static final int RIGHT_FIELD_NUMBER = 4;
    private double right_;
    /**
     * <code>double right = 4;</code>
     */
    public double getRight() {
      return right_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (top_ != 0D) {
        output.writeDouble(1, top_);
      }
      if (left_ != 0D) {
        output.writeDouble(2, left_);
      }
      if (bottom_ != 0D) {
        output.writeDouble(3, bottom_);
      }
      if (right_ != 0D) {
        output.writeDouble(4, right_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (top_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, top_);
      }
      if (left_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, left_);
      }
      if (bottom_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, bottom_);
      }
      if (right_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, right_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.gomatcha.matcha.pb.layout.PbLayout.Insets)) {
        return super.equals(obj);
      }
      io.gomatcha.matcha.pb.layout.PbLayout.Insets other = (io.gomatcha.matcha.pb.layout.PbLayout.Insets) obj;

      boolean result = true;
      result = result && (
          java.lang.Double.doubleToLongBits(getTop())
          == java.lang.Double.doubleToLongBits(
              other.getTop()));
      result = result && (
          java.lang.Double.doubleToLongBits(getLeft())
          == java.lang.Double.doubleToLongBits(
              other.getLeft()));
      result = result && (
          java.lang.Double.doubleToLongBits(getBottom())
          == java.lang.Double.doubleToLongBits(
              other.getBottom()));
      result = result && (
          java.lang.Double.doubleToLongBits(getRight())
          == java.lang.Double.doubleToLongBits(
              other.getRight()));
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TOP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getTop()));
      hash = (37 * hash) + LEFT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getLeft()));
      hash = (37 * hash) + BOTTOM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getBottom()));
      hash = (37 * hash) + RIGHT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getRight()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.gomatcha.matcha.pb.layout.PbLayout.Insets parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.gomatcha.matcha.pb.layout.PbLayout.Insets parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.gomatcha.matcha.pb.layout.PbLayout.Insets parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.gomatcha.matcha.pb.layout.PbLayout.Insets parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.gomatcha.matcha.pb.layout.PbLayout.Insets parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.gomatcha.matcha.pb.layout.PbLayout.Insets parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.gomatcha.matcha.pb.layout.PbLayout.Insets parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.gomatcha.matcha.pb.layout.PbLayout.Insets parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.gomatcha.matcha.pb.layout.PbLayout.Insets parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.gomatcha.matcha.pb.layout.PbLayout.Insets parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.gomatcha.matcha.pb.layout.PbLayout.Insets parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.gomatcha.matcha.pb.layout.PbLayout.Insets parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.gomatcha.matcha.pb.layout.PbLayout.Insets prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code matcha.layout.Insets}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:matcha.layout.Insets)
        io.gomatcha.matcha.pb.layout.PbLayout.InsetsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.gomatcha.matcha.pb.layout.PbLayout.internal_static_matcha_layout_Insets_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.gomatcha.matcha.pb.layout.PbLayout.internal_static_matcha_layout_Insets_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.gomatcha.matcha.pb.layout.PbLayout.Insets.class, io.gomatcha.matcha.pb.layout.PbLayout.Insets.Builder.class);
      }

      // Construct using io.gomatcha.matcha.pb.layout.PbLayout.Insets.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        top_ = 0D;

        left_ = 0D;

        bottom_ = 0D;

        right_ = 0D;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.gomatcha.matcha.pb.layout.PbLayout.internal_static_matcha_layout_Insets_descriptor;
      }

      public io.gomatcha.matcha.pb.layout.PbLayout.Insets getDefaultInstanceForType() {
        return io.gomatcha.matcha.pb.layout.PbLayout.Insets.getDefaultInstance();
      }

      public io.gomatcha.matcha.pb.layout.PbLayout.Insets build() {
        io.gomatcha.matcha.pb.layout.PbLayout.Insets result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.gomatcha.matcha.pb.layout.PbLayout.Insets buildPartial() {
        io.gomatcha.matcha.pb.layout.PbLayout.Insets result = new io.gomatcha.matcha.pb.layout.PbLayout.Insets(this);
        result.top_ = top_;
        result.left_ = left_;
        result.bottom_ = bottom_;
        result.right_ = right_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.gomatcha.matcha.pb.layout.PbLayout.Insets) {
          return mergeFrom((io.gomatcha.matcha.pb.layout.PbLayout.Insets)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.gomatcha.matcha.pb.layout.PbLayout.Insets other) {
        if (other == io.gomatcha.matcha.pb.layout.PbLayout.Insets.getDefaultInstance()) return this;
        if (other.getTop() != 0D) {
          setTop(other.getTop());
        }
        if (other.getLeft() != 0D) {
          setLeft(other.getLeft());
        }
        if (other.getBottom() != 0D) {
          setBottom(other.getBottom());
        }
        if (other.getRight() != 0D) {
          setRight(other.getRight());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.gomatcha.matcha.pb.layout.PbLayout.Insets parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.gomatcha.matcha.pb.layout.PbLayout.Insets) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private double top_ ;
      /**
       * <code>double top = 1;</code>
       */
      public double getTop() {
        return top_;
      }
      /**
       * <code>double top = 1;</code>
       */
      public Builder setTop(double value) {
        
        top_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double top = 1;</code>
       */
      public Builder clearTop() {
        
        top_ = 0D;
        onChanged();
        return this;
      }

      private double left_ ;
      /**
       * <code>double left = 2;</code>
       */
      public double getLeft() {
        return left_;
      }
      /**
       * <code>double left = 2;</code>
       */
      public Builder setLeft(double value) {
        
        left_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double left = 2;</code>
       */
      public Builder clearLeft() {
        
        left_ = 0D;
        onChanged();
        return this;
      }

      private double bottom_ ;
      /**
       * <code>double bottom = 3;</code>
       */
      public double getBottom() {
        return bottom_;
      }
      /**
       * <code>double bottom = 3;</code>
       */
      public Builder setBottom(double value) {
        
        bottom_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double bottom = 3;</code>
       */
      public Builder clearBottom() {
        
        bottom_ = 0D;
        onChanged();
        return this;
      }

      private double right_ ;
      /**
       * <code>double right = 4;</code>
       */
      public double getRight() {
        return right_;
      }
      /**
       * <code>double right = 4;</code>
       */
      public Builder setRight(double value) {
        
        right_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double right = 4;</code>
       */
      public Builder clearRight() {
        
        right_ = 0D;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:matcha.layout.Insets)
    }

    // @@protoc_insertion_point(class_scope:matcha.layout.Insets)
    private static final io.gomatcha.matcha.pb.layout.PbLayout.Insets DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.gomatcha.matcha.pb.layout.PbLayout.Insets();
    }

    public static io.gomatcha.matcha.pb.layout.PbLayout.Insets getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Insets>
        PARSER = new com.google.protobuf.AbstractParser<Insets>() {
      public Insets parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Insets(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Insets> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Insets> getParserForType() {
      return PARSER;
    }

    public io.gomatcha.matcha.pb.layout.PbLayout.Insets getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GuideOrBuilder extends
      // @@protoc_insertion_point(interface_extends:matcha.layout.Guide)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.matcha.layout.Rect frame = 1;</code>
     */
    boolean hasFrame();
    /**
     * <code>.matcha.layout.Rect frame = 1;</code>
     */
    io.gomatcha.matcha.pb.layout.PbLayout.Rect getFrame();
    /**
     * <code>.matcha.layout.Rect frame = 1;</code>
     */
    io.gomatcha.matcha.pb.layout.PbLayout.RectOrBuilder getFrameOrBuilder();

    /**
     * <code>int64 zIndex = 3;</code>
     */
    long getZIndex();
  }
  /**
   * Protobuf type {@code matcha.layout.Guide}
   */
  public  static final class Guide extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:matcha.layout.Guide)
      GuideOrBuilder {
    // Use Guide.newBuilder() to construct.
    private Guide(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Guide() {
      zIndex_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Guide(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              io.gomatcha.matcha.pb.layout.PbLayout.Rect.Builder subBuilder = null;
              if (frame_ != null) {
                subBuilder = frame_.toBuilder();
              }
              frame_ = input.readMessage(io.gomatcha.matcha.pb.layout.PbLayout.Rect.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(frame_);
                frame_ = subBuilder.buildPartial();
              }

              break;
            }
            case 24: {

              zIndex_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.gomatcha.matcha.pb.layout.PbLayout.internal_static_matcha_layout_Guide_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.gomatcha.matcha.pb.layout.PbLayout.internal_static_matcha_layout_Guide_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.gomatcha.matcha.pb.layout.PbLayout.Guide.class, io.gomatcha.matcha.pb.layout.PbLayout.Guide.Builder.class);
    }

    public static final int FRAME_FIELD_NUMBER = 1;
    private io.gomatcha.matcha.pb.layout.PbLayout.Rect frame_;
    /**
     * <code>.matcha.layout.Rect frame = 1;</code>
     */
    public boolean hasFrame() {
      return frame_ != null;
    }
    /**
     * <code>.matcha.layout.Rect frame = 1;</code>
     */
    public io.gomatcha.matcha.pb.layout.PbLayout.Rect getFrame() {
      return frame_ == null ? io.gomatcha.matcha.pb.layout.PbLayout.Rect.getDefaultInstance() : frame_;
    }
    /**
     * <code>.matcha.layout.Rect frame = 1;</code>
     */
    public io.gomatcha.matcha.pb.layout.PbLayout.RectOrBuilder getFrameOrBuilder() {
      return getFrame();
    }

    public static final int ZINDEX_FIELD_NUMBER = 3;
    private long zIndex_;
    /**
     * <code>int64 zIndex = 3;</code>
     */
    public long getZIndex() {
      return zIndex_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (frame_ != null) {
        output.writeMessage(1, getFrame());
      }
      if (zIndex_ != 0L) {
        output.writeInt64(3, zIndex_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (frame_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getFrame());
      }
      if (zIndex_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, zIndex_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.gomatcha.matcha.pb.layout.PbLayout.Guide)) {
        return super.equals(obj);
      }
      io.gomatcha.matcha.pb.layout.PbLayout.Guide other = (io.gomatcha.matcha.pb.layout.PbLayout.Guide) obj;

      boolean result = true;
      result = result && (hasFrame() == other.hasFrame());
      if (hasFrame()) {
        result = result && getFrame()
            .equals(other.getFrame());
      }
      result = result && (getZIndex()
          == other.getZIndex());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasFrame()) {
        hash = (37 * hash) + FRAME_FIELD_NUMBER;
        hash = (53 * hash) + getFrame().hashCode();
      }
      hash = (37 * hash) + ZINDEX_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getZIndex());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.gomatcha.matcha.pb.layout.PbLayout.Guide parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.gomatcha.matcha.pb.layout.PbLayout.Guide parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.gomatcha.matcha.pb.layout.PbLayout.Guide parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.gomatcha.matcha.pb.layout.PbLayout.Guide parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.gomatcha.matcha.pb.layout.PbLayout.Guide parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.gomatcha.matcha.pb.layout.PbLayout.Guide parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.gomatcha.matcha.pb.layout.PbLayout.Guide parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.gomatcha.matcha.pb.layout.PbLayout.Guide parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.gomatcha.matcha.pb.layout.PbLayout.Guide parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.gomatcha.matcha.pb.layout.PbLayout.Guide parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.gomatcha.matcha.pb.layout.PbLayout.Guide parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.gomatcha.matcha.pb.layout.PbLayout.Guide parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.gomatcha.matcha.pb.layout.PbLayout.Guide prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code matcha.layout.Guide}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:matcha.layout.Guide)
        io.gomatcha.matcha.pb.layout.PbLayout.GuideOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.gomatcha.matcha.pb.layout.PbLayout.internal_static_matcha_layout_Guide_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.gomatcha.matcha.pb.layout.PbLayout.internal_static_matcha_layout_Guide_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.gomatcha.matcha.pb.layout.PbLayout.Guide.class, io.gomatcha.matcha.pb.layout.PbLayout.Guide.Builder.class);
      }

      // Construct using io.gomatcha.matcha.pb.layout.PbLayout.Guide.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (frameBuilder_ == null) {
          frame_ = null;
        } else {
          frame_ = null;
          frameBuilder_ = null;
        }
        zIndex_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.gomatcha.matcha.pb.layout.PbLayout.internal_static_matcha_layout_Guide_descriptor;
      }

      public io.gomatcha.matcha.pb.layout.PbLayout.Guide getDefaultInstanceForType() {
        return io.gomatcha.matcha.pb.layout.PbLayout.Guide.getDefaultInstance();
      }

      public io.gomatcha.matcha.pb.layout.PbLayout.Guide build() {
        io.gomatcha.matcha.pb.layout.PbLayout.Guide result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.gomatcha.matcha.pb.layout.PbLayout.Guide buildPartial() {
        io.gomatcha.matcha.pb.layout.PbLayout.Guide result = new io.gomatcha.matcha.pb.layout.PbLayout.Guide(this);
        if (frameBuilder_ == null) {
          result.frame_ = frame_;
        } else {
          result.frame_ = frameBuilder_.build();
        }
        result.zIndex_ = zIndex_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.gomatcha.matcha.pb.layout.PbLayout.Guide) {
          return mergeFrom((io.gomatcha.matcha.pb.layout.PbLayout.Guide)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.gomatcha.matcha.pb.layout.PbLayout.Guide other) {
        if (other == io.gomatcha.matcha.pb.layout.PbLayout.Guide.getDefaultInstance()) return this;
        if (other.hasFrame()) {
          mergeFrame(other.getFrame());
        }
        if (other.getZIndex() != 0L) {
          setZIndex(other.getZIndex());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.gomatcha.matcha.pb.layout.PbLayout.Guide parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.gomatcha.matcha.pb.layout.PbLayout.Guide) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private io.gomatcha.matcha.pb.layout.PbLayout.Rect frame_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          io.gomatcha.matcha.pb.layout.PbLayout.Rect, io.gomatcha.matcha.pb.layout.PbLayout.Rect.Builder, io.gomatcha.matcha.pb.layout.PbLayout.RectOrBuilder> frameBuilder_;
      /**
       * <code>.matcha.layout.Rect frame = 1;</code>
       */
      public boolean hasFrame() {
        return frameBuilder_ != null || frame_ != null;
      }
      /**
       * <code>.matcha.layout.Rect frame = 1;</code>
       */
      public io.gomatcha.matcha.pb.layout.PbLayout.Rect getFrame() {
        if (frameBuilder_ == null) {
          return frame_ == null ? io.gomatcha.matcha.pb.layout.PbLayout.Rect.getDefaultInstance() : frame_;
        } else {
          return frameBuilder_.getMessage();
        }
      }
      /**
       * <code>.matcha.layout.Rect frame = 1;</code>
       */
      public Builder setFrame(io.gomatcha.matcha.pb.layout.PbLayout.Rect value) {
        if (frameBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          frame_ = value;
          onChanged();
        } else {
          frameBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.matcha.layout.Rect frame = 1;</code>
       */
      public Builder setFrame(
          io.gomatcha.matcha.pb.layout.PbLayout.Rect.Builder builderForValue) {
        if (frameBuilder_ == null) {
          frame_ = builderForValue.build();
          onChanged();
        } else {
          frameBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.matcha.layout.Rect frame = 1;</code>
       */
      public Builder mergeFrame(io.gomatcha.matcha.pb.layout.PbLayout.Rect value) {
        if (frameBuilder_ == null) {
          if (frame_ != null) {
            frame_ =
              io.gomatcha.matcha.pb.layout.PbLayout.Rect.newBuilder(frame_).mergeFrom(value).buildPartial();
          } else {
            frame_ = value;
          }
          onChanged();
        } else {
          frameBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.matcha.layout.Rect frame = 1;</code>
       */
      public Builder clearFrame() {
        if (frameBuilder_ == null) {
          frame_ = null;
          onChanged();
        } else {
          frame_ = null;
          frameBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.matcha.layout.Rect frame = 1;</code>
       */
      public io.gomatcha.matcha.pb.layout.PbLayout.Rect.Builder getFrameBuilder() {
        
        onChanged();
        return getFrameFieldBuilder().getBuilder();
      }
      /**
       * <code>.matcha.layout.Rect frame = 1;</code>
       */
      public io.gomatcha.matcha.pb.layout.PbLayout.RectOrBuilder getFrameOrBuilder() {
        if (frameBuilder_ != null) {
          return frameBuilder_.getMessageOrBuilder();
        } else {
          return frame_ == null ?
              io.gomatcha.matcha.pb.layout.PbLayout.Rect.getDefaultInstance() : frame_;
        }
      }
      /**
       * <code>.matcha.layout.Rect frame = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          io.gomatcha.matcha.pb.layout.PbLayout.Rect, io.gomatcha.matcha.pb.layout.PbLayout.Rect.Builder, io.gomatcha.matcha.pb.layout.PbLayout.RectOrBuilder> 
          getFrameFieldBuilder() {
        if (frameBuilder_ == null) {
          frameBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              io.gomatcha.matcha.pb.layout.PbLayout.Rect, io.gomatcha.matcha.pb.layout.PbLayout.Rect.Builder, io.gomatcha.matcha.pb.layout.PbLayout.RectOrBuilder>(
                  getFrame(),
                  getParentForChildren(),
                  isClean());
          frame_ = null;
        }
        return frameBuilder_;
      }

      private long zIndex_ ;
      /**
       * <code>int64 zIndex = 3;</code>
       */
      public long getZIndex() {
        return zIndex_;
      }
      /**
       * <code>int64 zIndex = 3;</code>
       */
      public Builder setZIndex(long value) {
        
        zIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 zIndex = 3;</code>
       */
      public Builder clearZIndex() {
        
        zIndex_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:matcha.layout.Guide)
    }

    // @@protoc_insertion_point(class_scope:matcha.layout.Guide)
    private static final io.gomatcha.matcha.pb.layout.PbLayout.Guide DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.gomatcha.matcha.pb.layout.PbLayout.Guide();
    }

    public static io.gomatcha.matcha.pb.layout.PbLayout.Guide getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Guide>
        PARSER = new com.google.protobuf.AbstractParser<Guide>() {
      public Guide parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Guide(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Guide> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Guide> getParserForType() {
      return PARSER;
    }

    public io.gomatcha.matcha.pb.layout.PbLayout.Guide getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_matcha_layout_Point_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_matcha_layout_Point_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_matcha_layout_Rect_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_matcha_layout_Rect_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_matcha_layout_Insets_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_matcha_layout_Insets_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_matcha_layout_Guide_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_matcha_layout_Guide_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n)gomatcha.io/matcha/pb/layout/layout.pr" +
      "oto\022\rmatcha.layout\"\035\n\005Point\022\t\n\001x\030\001 \001(\001\022\t" +
      "\n\001y\030\002 \001(\001\"L\n\004Rect\022!\n\003min\030\001 \001(\0132\024.matcha." +
      "layout.Point\022!\n\003max\030\002 \001(\0132\024.matcha.layou" +
      "t.Point\"B\n\006Insets\022\013\n\003top\030\001 \001(\001\022\014\n\004left\030\002" +
      " \001(\001\022\016\n\006bottom\030\003 \001(\001\022\r\n\005right\030\004 \001(\001\";\n\005G" +
      "uide\022\"\n\005frame\030\001 \001(\0132\023.matcha.layout.Rect" +
      "\022\016\n\006zIndex\030\003 \001(\003BA\n\034io.gomatcha.matcha.p" +
      "b.layoutB\010PbLayoutZ\006layout\242\002\016MatchaLayou" +
      "tPBb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_matcha_layout_Point_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_matcha_layout_Point_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_matcha_layout_Point_descriptor,
        new java.lang.String[] { "X", "Y", });
    internal_static_matcha_layout_Rect_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_matcha_layout_Rect_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_matcha_layout_Rect_descriptor,
        new java.lang.String[] { "Min", "Max", });
    internal_static_matcha_layout_Insets_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_matcha_layout_Insets_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_matcha_layout_Insets_descriptor,
        new java.lang.String[] { "Top", "Left", "Bottom", "Right", });
    internal_static_matcha_layout_Guide_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_matcha_layout_Guide_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_matcha_layout_Guide_descriptor,
        new java.lang.String[] { "Frame", "ZIndex", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
