// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gomatcha.io/matcha/pb/text/text.proto

/*
Package text is a generated protocol buffer package.

It is generated from these files:
	gomatcha.io/matcha/pb/text/text.proto

It has these top-level messages:
	SizeFunc
	Text
	StyledText
	Font
	TextStyle
*/
package text

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import matcha_layout "gomatcha.io/matcha/pb/layout"
import matcha "gomatcha.io/matcha/pb"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TextAlignment int32

const (
	TextAlignment_TEXT_ALIGNMENT_LEFT      TextAlignment = 0
	TextAlignment_TEXT_ALIGNMENT_RIGHT     TextAlignment = 1
	TextAlignment_TEXT_ALIGNMENT_CENTER    TextAlignment = 2
	TextAlignment_TEXT_ALIGNMENT_JUSTIFIED TextAlignment = 3
)

var TextAlignment_name = map[int32]string{
	0: "TEXT_ALIGNMENT_LEFT",
	1: "TEXT_ALIGNMENT_RIGHT",
	2: "TEXT_ALIGNMENT_CENTER",
	3: "TEXT_ALIGNMENT_JUSTIFIED",
}
var TextAlignment_value = map[string]int32{
	"TEXT_ALIGNMENT_LEFT":      0,
	"TEXT_ALIGNMENT_RIGHT":     1,
	"TEXT_ALIGNMENT_CENTER":    2,
	"TEXT_ALIGNMENT_JUSTIFIED": 3,
}

func (x TextAlignment) String() string {
	return proto.EnumName(TextAlignment_name, int32(x))
}
func (TextAlignment) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type StrikethroughStyle int32

const (
	StrikethroughStyle_STRIKETHROUGH_STYLE_NONE   StrikethroughStyle = 0
	StrikethroughStyle_STRIKETHROUGH_STYLE_SINGLE StrikethroughStyle = 1
	StrikethroughStyle_STRIKETHROUGH_STYLE_DOUBLE StrikethroughStyle = 2
	StrikethroughStyle_STRIKETHROUGH_STYLE_THICK  StrikethroughStyle = 3
	StrikethroughStyle_STRIKETHROUGH_STYLE_DOTTED StrikethroughStyle = 4
	StrikethroughStyle_STRIKETHROUGH_STYLE_DASHED StrikethroughStyle = 5
)

var StrikethroughStyle_name = map[int32]string{
	0: "STRIKETHROUGH_STYLE_NONE",
	1: "STRIKETHROUGH_STYLE_SINGLE",
	2: "STRIKETHROUGH_STYLE_DOUBLE",
	3: "STRIKETHROUGH_STYLE_THICK",
	4: "STRIKETHROUGH_STYLE_DOTTED",
	5: "STRIKETHROUGH_STYLE_DASHED",
}
var StrikethroughStyle_value = map[string]int32{
	"STRIKETHROUGH_STYLE_NONE":   0,
	"STRIKETHROUGH_STYLE_SINGLE": 1,
	"STRIKETHROUGH_STYLE_DOUBLE": 2,
	"STRIKETHROUGH_STYLE_THICK":  3,
	"STRIKETHROUGH_STYLE_DOTTED": 4,
	"STRIKETHROUGH_STYLE_DASHED": 5,
}

func (x StrikethroughStyle) String() string {
	return proto.EnumName(StrikethroughStyle_name, int32(x))
}
func (StrikethroughStyle) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type UnderlineStyle int32

const (
	UnderlineStyle_UNDRELINE_STYLE_NONE   UnderlineStyle = 0
	UnderlineStyle_UNDRELINE_STYLE_SINGLE UnderlineStyle = 1
	UnderlineStyle_UNDRELINE_STYLE_DOUBLE UnderlineStyle = 2
	UnderlineStyle_UNDRELINE_STYLE_THICK  UnderlineStyle = 3
	UnderlineStyle_UNDRELINE_STYLE_DOTTED UnderlineStyle = 4
	UnderlineStyle_UNDRELINE_STYLE_DASHED UnderlineStyle = 5
)

var UnderlineStyle_name = map[int32]string{
	0: "UNDRELINE_STYLE_NONE",
	1: "UNDRELINE_STYLE_SINGLE",
	2: "UNDRELINE_STYLE_DOUBLE",
	3: "UNDRELINE_STYLE_THICK",
	4: "UNDRELINE_STYLE_DOTTED",
	5: "UNDRELINE_STYLE_DASHED",
}
var UnderlineStyle_value = map[string]int32{
	"UNDRELINE_STYLE_NONE":   0,
	"UNDRELINE_STYLE_SINGLE": 1,
	"UNDRELINE_STYLE_DOUBLE": 2,
	"UNDRELINE_STYLE_THICK":  3,
	"UNDRELINE_STYLE_DOTTED": 4,
	"UNDRELINE_STYLE_DASHED": 5,
}

func (x UnderlineStyle) String() string {
	return proto.EnumName(UnderlineStyle_name, int32(x))
}
func (UnderlineStyle) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type TextWrap int32

const (
	TextWrap_TEXT_WRAP_NONE      TextWrap = 0
	TextWrap_TEXT_WRAP_WORD      TextWrap = 1
	TextWrap_TEXT_WRAP_CHARACTER TextWrap = 2
)

var TextWrap_name = map[int32]string{
	0: "TEXT_WRAP_NONE",
	1: "TEXT_WRAP_WORD",
	2: "TEXT_WRAP_CHARACTER",
}
var TextWrap_value = map[string]int32{
	"TEXT_WRAP_NONE":      0,
	"TEXT_WRAP_WORD":      1,
	"TEXT_WRAP_CHARACTER": 2,
}

func (x TextWrap) String() string {
	return proto.EnumName(TextWrap_name, int32(x))
}
func (TextWrap) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type Truncation int32

const (
	Truncation_TRUNCATION_NONE   Truncation = 0
	Truncation_TRUNCATION_START  Truncation = 1
	Truncation_TRUNCATION_MIDDLE Truncation = 2
	Truncation_TRUNCATION_END    Truncation = 3
)

var Truncation_name = map[int32]string{
	0: "TRUNCATION_NONE",
	1: "TRUNCATION_START",
	2: "TRUNCATION_MIDDLE",
	3: "TRUNCATION_END",
}
var Truncation_value = map[string]int32{
	"TRUNCATION_NONE":   0,
	"TRUNCATION_START":  1,
	"TRUNCATION_MIDDLE": 2,
	"TRUNCATION_END":    3,
}

func (x Truncation) String() string {
	return proto.EnumName(Truncation_name, int32(x))
}
func (Truncation) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type SizeFunc struct {
	Text    *StyledText          `protobuf:"bytes,1,opt,name=text" json:"text,omitempty"`
	MinSize *matcha_layout.Point `protobuf:"bytes,2,opt,name=minSize" json:"minSize,omitempty"`
	MaxSize *matcha_layout.Point `protobuf:"bytes,3,opt,name=maxSize" json:"maxSize,omitempty"`
}

func (m *SizeFunc) Reset()                    { *m = SizeFunc{} }
func (m *SizeFunc) String() string            { return proto.CompactTextString(m) }
func (*SizeFunc) ProtoMessage()               {}
func (*SizeFunc) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SizeFunc) GetText() *StyledText {
	if m != nil {
		return m.Text
	}
	return nil
}

func (m *SizeFunc) GetMinSize() *matcha_layout.Point {
	if m != nil {
		return m.MinSize
	}
	return nil
}

func (m *SizeFunc) GetMaxSize() *matcha_layout.Point {
	if m != nil {
		return m.MaxSize
	}
	return nil
}

type Text struct {
	Text string `protobuf:"bytes,1,opt,name=text" json:"text,omitempty"`
}

func (m *Text) Reset()                    { *m = Text{} }
func (m *Text) String() string            { return proto.CompactTextString(m) }
func (*Text) ProtoMessage()               {}
func (*Text) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Text) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type StyledText struct {
	Style *TextStyle `protobuf:"bytes,1,opt,name=style" json:"style,omitempty"`
	Text  *Text      `protobuf:"bytes,2,opt,name=text" json:"text,omitempty"`
}

func (m *StyledText) Reset()                    { *m = StyledText{} }
func (m *StyledText) String() string            { return proto.CompactTextString(m) }
func (*StyledText) ProtoMessage()               {}
func (*StyledText) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *StyledText) GetStyle() *TextStyle {
	if m != nil {
		return m.Style
	}
	return nil
}

func (m *StyledText) GetText() *Text {
	if m != nil {
		return m.Text
	}
	return nil
}

type Font struct {
	Family string  `protobuf:"bytes,1,opt,name=family" json:"family,omitempty"`
	Face   string  `protobuf:"bytes,2,opt,name=face" json:"face,omitempty"`
	Size   float64 `protobuf:"fixed64,3,opt,name=size" json:"size,omitempty"`
}

func (m *Font) Reset()                    { *m = Font{} }
func (m *Font) String() string            { return proto.CompactTextString(m) }
func (*Font) ProtoMessage()               {}
func (*Font) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Font) GetFamily() string {
	if m != nil {
		return m.Family
	}
	return ""
}

func (m *Font) GetFace() string {
	if m != nil {
		return m.Face
	}
	return ""
}

func (m *Font) GetSize() float64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type TextStyle struct {
	TextAlignment      TextAlignment      `protobuf:"varint,2,opt,name=textAlignment,enum=matcha.text.TextAlignment" json:"textAlignment,omitempty"`
	StrikethroughStyle StrikethroughStyle `protobuf:"varint,4,opt,name=strikethroughStyle,enum=matcha.text.StrikethroughStyle" json:"strikethroughStyle,omitempty"`
	StrikethroughColor *matcha.Color      `protobuf:"bytes,6,opt,name=strikethroughColor" json:"strikethroughColor,omitempty"`
	UnderlineStyle     UnderlineStyle     `protobuf:"varint,8,opt,name=underlineStyle,enum=matcha.text.UnderlineStyle" json:"underlineStyle,omitempty"`
	UnderlineColor     *matcha.Color      `protobuf:"bytes,10,opt,name=underlineColor" json:"underlineColor,omitempty"`
	Font               *Font              `protobuf:"bytes,12,opt,name=font" json:"font,omitempty"`
	Hyphenation        float64            `protobuf:"fixed64,14,opt,name=hyphenation" json:"hyphenation,omitempty"`
	LineHeightMultiple float64            `protobuf:"fixed64,16,opt,name=lineHeightMultiple" json:"lineHeightMultiple,omitempty"`
	MaxLines           int64              `protobuf:"varint,18,opt,name=maxLines" json:"maxLines,omitempty"`
	TextColor          *matcha.Color      `protobuf:"bytes,20,opt,name=textColor" json:"textColor,omitempty"`
	Wrap               TextWrap           `protobuf:"varint,22,opt,name=wrap,enum=matcha.text.TextWrap" json:"wrap,omitempty"`
	Truncation         Truncation         `protobuf:"varint,24,opt,name=truncation,enum=matcha.text.Truncation" json:"truncation,omitempty"`
	TruncationString   string             `protobuf:"bytes,26,opt,name=truncationString" json:"truncationString,omitempty"`
}

func (m *TextStyle) Reset()                    { *m = TextStyle{} }
func (m *TextStyle) String() string            { return proto.CompactTextString(m) }
func (*TextStyle) ProtoMessage()               {}
func (*TextStyle) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *TextStyle) GetTextAlignment() TextAlignment {
	if m != nil {
		return m.TextAlignment
	}
	return TextAlignment_TEXT_ALIGNMENT_LEFT
}

func (m *TextStyle) GetStrikethroughStyle() StrikethroughStyle {
	if m != nil {
		return m.StrikethroughStyle
	}
	return StrikethroughStyle_STRIKETHROUGH_STYLE_NONE
}

func (m *TextStyle) GetStrikethroughColor() *matcha.Color {
	if m != nil {
		return m.StrikethroughColor
	}
	return nil
}

func (m *TextStyle) GetUnderlineStyle() UnderlineStyle {
	if m != nil {
		return m.UnderlineStyle
	}
	return UnderlineStyle_UNDRELINE_STYLE_NONE
}

func (m *TextStyle) GetUnderlineColor() *matcha.Color {
	if m != nil {
		return m.UnderlineColor
	}
	return nil
}

func (m *TextStyle) GetFont() *Font {
	if m != nil {
		return m.Font
	}
	return nil
}

func (m *TextStyle) GetHyphenation() float64 {
	if m != nil {
		return m.Hyphenation
	}
	return 0
}

func (m *TextStyle) GetLineHeightMultiple() float64 {
	if m != nil {
		return m.LineHeightMultiple
	}
	return 0
}

func (m *TextStyle) GetMaxLines() int64 {
	if m != nil {
		return m.MaxLines
	}
	return 0
}

func (m *TextStyle) GetTextColor() *matcha.Color {
	if m != nil {
		return m.TextColor
	}
	return nil
}

func (m *TextStyle) GetWrap() TextWrap {
	if m != nil {
		return m.Wrap
	}
	return TextWrap_TEXT_WRAP_NONE
}

func (m *TextStyle) GetTruncation() Truncation {
	if m != nil {
		return m.Truncation
	}
	return Truncation_TRUNCATION_NONE
}

func (m *TextStyle) GetTruncationString() string {
	if m != nil {
		return m.TruncationString
	}
	return ""
}

func init() {
	proto.RegisterType((*SizeFunc)(nil), "matcha.text.SizeFunc")
	proto.RegisterType((*Text)(nil), "matcha.text.Text")
	proto.RegisterType((*StyledText)(nil), "matcha.text.StyledText")
	proto.RegisterType((*Font)(nil), "matcha.text.Font")
	proto.RegisterType((*TextStyle)(nil), "matcha.text.TextStyle")
	proto.RegisterEnum("matcha.text.TextAlignment", TextAlignment_name, TextAlignment_value)
	proto.RegisterEnum("matcha.text.StrikethroughStyle", StrikethroughStyle_name, StrikethroughStyle_value)
	proto.RegisterEnum("matcha.text.UnderlineStyle", UnderlineStyle_name, UnderlineStyle_value)
	proto.RegisterEnum("matcha.text.TextWrap", TextWrap_name, TextWrap_value)
	proto.RegisterEnum("matcha.text.Truncation", Truncation_name, Truncation_value)
}

func init() { proto.RegisterFile("gomatcha.io/matcha/pb/text/text.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 819 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x55, 0x5d, 0x6f, 0xe2, 0x56,
	0x10, 0x5d, 0x07, 0x92, 0x92, 0x49, 0x43, 0xbd, 0xb3, 0x49, 0xd6, 0x71, 0xbf, 0xd2, 0x48, 0x2b,
	0xed, 0xb2, 0x15, 0x91, 0xb6, 0x5a, 0xf5, 0xa9, 0x52, 0x1d, 0x7c, 0x09, 0x6e, 0x88, 0x89, 0xae,
	0x2f, 0x4a, 0xdb, 0x97, 0xc8, 0x64, 0x1d, 0xb0, 0x6a, 0x6c, 0x64, 0x2e, 0x2a, 0xb4, 0x3f, 0xa4,
	0xef, 0x7d, 0xed, 0x73, 0x7f, 0x48, 0xff, 0x51, 0x75, 0xaf, 0x3f, 0xc0, 0xc6, 0xd9, 0x17, 0xec,
	0x3b, 0xe7, 0xcc, 0xcc, 0x19, 0xcf, 0x31, 0x86, 0x57, 0xe3, 0x68, 0xea, 0xf2, 0x87, 0x89, 0xdb,
	0xf6, 0xa3, 0x8b, 0xe4, 0xee, 0x62, 0x36, 0xba, 0xe0, 0xde, 0x92, 0xcb, 0x9f, 0xf6, 0x2c, 0x8e,
	0x78, 0x84, 0x07, 0x29, 0x49, 0x84, 0xf4, 0x37, 0xd5, 0x39, 0x81, 0xbb, 0x8a, 0x16, 0x3c, 0xbd,
	0x24, 0x79, 0xfa, 0x37, 0xd5, 0x54, 0x7f, 0xea, 0x8e, 0xbd, 0x84, 0x72, 0xfe, 0x97, 0x02, 0x0d,
	0xc7, 0xff, 0xc3, 0xeb, 0x2e, 0xc2, 0x07, 0x7c, 0x0b, 0x75, 0xd1, 0x42, 0x53, 0xce, 0x94, 0xd7,
	0x07, 0xef, 0x5e, 0xb6, 0x37, 0xda, 0xb6, 0x1d, 0xbe, 0x0a, 0xbc, 0x0f, 0xcc, 0x5b, 0x72, 0x2a,
	0x49, 0xd8, 0x86, 0x4f, 0xa6, 0x7e, 0x28, 0x72, 0xb5, 0x1d, 0xc9, 0x3f, 0xca, 0xf8, 0xa9, 0x86,
	0xdb, 0xc8, 0x0f, 0x39, 0xcd, 0x48, 0x92, 0xef, 0x2e, 0x25, 0xbf, 0xf6, 0x51, 0x7e, 0x42, 0x3a,
	0xd7, 0xa1, 0x2e, 0xba, 0x21, 0x6e, 0x88, 0xda, 0x4f, 0x7a, 0x9f, 0xbb, 0x00, 0x6b, 0x3d, 0xf8,
	0x2d, 0xec, 0xce, 0xc5, 0x29, 0xd5, 0x7d, 0x52, 0xd0, 0x2d, 0x18, 0x92, 0x4b, 0x13, 0x12, 0xbe,
	0x4a, 0xeb, 0x25, 0xa2, 0x9f, 0x6f, 0x91, 0xd3, 0x16, 0x5d, 0xa8, 0x77, 0xa3, 0x90, 0xe3, 0x09,
	0xec, 0x3d, 0xba, 0x53, 0x3f, 0x58, 0xa5, 0x02, 0xd2, 0x93, 0x90, 0xf5, 0xe8, 0x3e, 0x24, 0xb3,
	0xef, 0x53, 0x79, 0x2f, 0x62, 0xf3, 0x6c, 0x3e, 0x85, 0xca, 0xfb, 0xf3, 0x7f, 0x76, 0x61, 0x3f,
	0xd7, 0x80, 0x3f, 0xc2, 0xa1, 0xa8, 0x6e, 0x04, 0xfe, 0x38, 0x9c, 0x7a, 0x61, 0xa2, 0xa2, 0xf9,
	0x4e, 0xdf, 0x52, 0x91, 0x33, 0x68, 0x31, 0x01, 0x07, 0x80, 0x73, 0x1e, 0xfb, 0xbf, 0x79, 0x7c,
	0x12, 0x47, 0x8b, 0xf1, 0x44, 0xd6, 0xd5, 0xea, 0xb2, 0xcc, 0xd7, 0xa5, 0x8d, 0x95, 0x69, 0xb4,
	0x22, 0x15, 0x7f, 0x28, 0x15, 0xec, 0x44, 0x41, 0x14, 0x6b, 0x7b, 0xf2, 0xe9, 0x1c, 0x66, 0x05,
	0x65, 0x90, 0x56, 0x10, 0xb1, 0x03, 0xcd, 0x45, 0xf8, 0xc1, 0x8b, 0x03, 0x3f, 0xf4, 0x12, 0x2d,
	0x0d, 0xa9, 0xe5, 0xf3, 0x82, 0x96, 0x61, 0x81, 0x42, 0x4b, 0x29, 0xf8, 0x7e, 0xa3, 0x48, 0xd2,
	0x1f, 0xaa, 0xfa, 0x97, 0x48, 0x62, 0x95, 0x8f, 0x51, 0xc8, 0xb5, 0x4f, 0x2b, 0x56, 0x29, 0x96,
	0x47, 0x25, 0x8c, 0x67, 0x70, 0x30, 0x59, 0xcd, 0x26, 0x5e, 0xe8, 0x72, 0x3f, 0x0a, 0xb5, 0xa6,
	0xdc, 0xce, 0x66, 0x08, 0xdb, 0x80, 0xa2, 0x6a, 0xcf, 0xf3, 0xc7, 0x13, 0x7e, 0xb3, 0x08, 0xb8,
	0x3f, 0x0b, 0x3c, 0x4d, 0x95, 0xc4, 0x0a, 0x04, 0x75, 0x68, 0x4c, 0xdd, 0x65, 0xdf, 0x0f, 0xbd,
	0xb9, 0x86, 0x67, 0xca, 0xeb, 0x1a, 0xcd, 0xcf, 0xf8, 0x16, 0xf6, 0x85, 0x80, 0x64, 0x8c, 0xa3,
	0xaa, 0x31, 0xd6, 0x38, 0xbe, 0x81, 0xfa, 0xef, 0xb1, 0x3b, 0xd3, 0x4e, 0xe4, 0x33, 0x3b, 0xde,
	0xb2, 0xc1, 0x5d, 0xec, 0xce, 0xa8, 0xa4, 0xe0, 0xf7, 0x00, 0x3c, 0x5e, 0x84, 0x0f, 0xc9, 0x10,
	0x9a, 0x4c, 0x28, 0xbe, 0xa2, 0x2c, 0x87, 0xe9, 0x06, 0x15, 0x5b, 0xa0, 0xae, 0x4f, 0xc2, 0x14,
	0xe1, 0x58, 0xd3, 0xa5, 0x6b, 0xb7, 0xe2, 0xad, 0x3f, 0xe1, 0xb0, 0xe0, 0x3e, 0x7c, 0x09, 0x2f,
	0x18, 0xf9, 0x99, 0xdd, 0x1b, 0x7d, 0xeb, 0xca, 0xbe, 0x21, 0x36, 0xbb, 0xef, 0x93, 0x2e, 0x53,
	0x9f, 0xa1, 0x06, 0x47, 0x25, 0x80, 0x5a, 0x57, 0x3d, 0xa6, 0x2a, 0x78, 0x0a, 0xc7, 0x25, 0xa4,
	0x43, 0x6c, 0x46, 0xa8, 0xba, 0x83, 0x5f, 0x80, 0x56, 0x82, 0x7e, 0x1a, 0x3a, 0xcc, 0xea, 0x5a,
	0xc4, 0x54, 0x6b, 0xad, 0xff, 0x14, 0xc0, 0x6d, 0xd3, 0x8a, 0x24, 0x87, 0x51, 0xeb, 0x9a, 0xb0,
	0x1e, 0x1d, 0x0c, 0xaf, 0x7a, 0xf7, 0x0e, 0xfb, 0xa5, 0x4f, 0xee, 0xed, 0x81, 0x4d, 0xd4, 0x67,
	0xf8, 0x15, 0xe8, 0x55, 0xa8, 0x63, 0xd9, 0x57, 0x7d, 0xa2, 0x2a, 0x4f, 0xe1, 0xe6, 0x60, 0x78,
	0xd9, 0x27, 0xea, 0x0e, 0x7e, 0x09, 0xa7, 0x55, 0x38, 0xeb, 0x59, 0x9d, 0x6b, 0xb5, 0xf6, 0x74,
	0x3a, 0x63, 0xc4, 0x54, 0xeb, 0x4f, 0xe2, 0x86, 0xd3, 0x23, 0xa6, 0xba, 0xdb, 0xfa, 0x57, 0x81,
	0x66, 0xd1, 0xfc, 0xe2, 0xc9, 0x0d, 0x6d, 0x93, 0x92, 0xbe, 0x65, 0x93, 0xe2, 0x2c, 0x3a, 0x9c,
	0x94, 0x91, 0x7c, 0x8e, 0x0a, 0x2c, 0x9f, 0xe1, 0x14, 0x8e, 0xcb, 0x58, 0xa6, 0xbf, 0x32, 0x2d,
	0xd5, 0x5e, 0x85, 0x65, 0xba, 0xaf, 0xa1, 0x91, 0xf9, 0x0f, 0x11, 0x9a, 0x72, 0x6b, 0x77, 0xd4,
	0xb8, 0xcd, 0xa4, 0x16, 0x62, 0x77, 0x03, 0x6a, 0xaa, 0x4a, 0xee, 0x15, 0x19, 0xeb, 0xf4, 0x0c,
	0x6a, 0x74, 0xe4, 0xda, 0x5b, 0x23, 0x80, 0xb5, 0x37, 0xf1, 0x05, 0x7c, 0xc6, 0xe8, 0xd0, 0xee,
	0x18, 0xcc, 0x1a, 0xd8, 0x59, 0xbd, 0x23, 0x50, 0x37, 0x82, 0x0e, 0x33, 0xa8, 0xb0, 0xd2, 0x31,
	0x3c, 0xdf, 0x88, 0xde, 0x58, 0xa6, 0x29, 0xe7, 0x15, 0xcd, 0xd7, 0x61, 0x62, 0x9b, 0x6a, 0xed,
	0xf2, 0x3d, 0xe8, 0x7e, 0xd4, 0xce, 0x3f, 0x78, 0xe9, 0x65, 0x36, 0x92, 0xaf, 0xc6, 0xe5, 0xde,
	0xed, 0x48, 0x8c, 0xf3, 0xab, 0xfc, 0x6f, 0xff, 0x7b, 0xa7, 0x71, 0x23, 0xe1, 0xdb, 0xcb, 0xd1,
	0x9e, 0xfc, 0x0c, 0x7e, 0xf7, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe5, 0x49, 0x4c, 0x9a, 0x8a,
	0x07, 0x00, 0x00,
}
