// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/gomatcha/matcha/proto/view/switchview.proto

package view

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SwitchView struct {
	Value                bool     `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Enabled              bool     `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SwitchView) Reset()         { *m = SwitchView{} }
func (m *SwitchView) String() string { return proto.CompactTextString(m) }
func (*SwitchView) ProtoMessage()    {}
func (*SwitchView) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b1a01bbd0100e1f, []int{0}
}
func (m *SwitchView) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SwitchView.Unmarshal(m, b)
}
func (m *SwitchView) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SwitchView.Marshal(b, m, deterministic)
}
func (m *SwitchView) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SwitchView.Merge(m, src)
}
func (m *SwitchView) XXX_Size() int {
	return xxx_messageInfo_SwitchView.Size(m)
}
func (m *SwitchView) XXX_DiscardUnknown() {
	xxx_messageInfo_SwitchView.DiscardUnknown(m)
}

var xxx_messageInfo_SwitchView proto.InternalMessageInfo

func (m *SwitchView) GetValue() bool {
	if m != nil {
		return m.Value
	}
	return false
}

func (m *SwitchView) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

type SwitchEvent struct {
	Value                bool     `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SwitchEvent) Reset()         { *m = SwitchEvent{} }
func (m *SwitchEvent) String() string { return proto.CompactTextString(m) }
func (*SwitchEvent) ProtoMessage()    {}
func (*SwitchEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b1a01bbd0100e1f, []int{1}
}
func (m *SwitchEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SwitchEvent.Unmarshal(m, b)
}
func (m *SwitchEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SwitchEvent.Marshal(b, m, deterministic)
}
func (m *SwitchEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SwitchEvent.Merge(m, src)
}
func (m *SwitchEvent) XXX_Size() int {
	return xxx_messageInfo_SwitchEvent.Size(m)
}
func (m *SwitchEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_SwitchEvent.DiscardUnknown(m)
}

var xxx_messageInfo_SwitchEvent proto.InternalMessageInfo

func (m *SwitchEvent) GetValue() bool {
	if m != nil {
		return m.Value
	}
	return false
}

func init() {
	proto.RegisterType((*SwitchView)(nil), "matcha.view.SwitchView")
	proto.RegisterType((*SwitchEvent)(nil), "matcha.view.SwitchEvent")
}

func init() {
	proto.RegisterFile("github.com/gomatcha/matcha/proto/view/switchview.proto", fileDescriptor_2b1a01bbd0100e1f)
}

var fileDescriptor_2b1a01bbd0100e1f = []byte{
	// 180 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0x4b, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0x4f, 0xcf, 0xcf, 0x4d, 0x2c, 0x49, 0xce, 0x48, 0xd4,
	0x87, 0x52, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0xfa, 0x65, 0x99, 0xa9, 0xe5, 0xfa, 0xc5, 0xe5, 0x99,
	0x25, 0xc9, 0x19, 0x20, 0xa6, 0x1e, 0x58, 0x54, 0x88, 0x1b, 0xa2, 0x46, 0x0f, 0x24, 0xa4, 0x64,
	0xc3, 0xc5, 0x15, 0x0c, 0x56, 0x10, 0x96, 0x99, 0x5a, 0x2e, 0x24, 0xc2, 0xc5, 0x5a, 0x96, 0x98,
	0x53, 0x9a, 0x2a, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x11, 0x04, 0xe1, 0x08, 0x49, 0x70, 0xb1, 0xa7,
	0xe6, 0x25, 0x26, 0xe5, 0xa4, 0xa6, 0x48, 0x30, 0x81, 0xc5, 0x61, 0x5c, 0x25, 0x65, 0x2e, 0x6e,
	0x88, 0x6e, 0xd7, 0xb2, 0xd4, 0xbc, 0x12, 0xec, 0xda, 0x9d, 0xbc, 0xb8, 0x54, 0x93, 0xf3, 0x73,
	0xf5, 0xa0, 0xae, 0x85, 0xb9, 0x54, 0x0f, 0x4a, 0x81, 0xdd, 0x04, 0x76, 0x8b, 0x13, 0x4f, 0x40,
	0x12, 0xc2, 0x2d, 0x51, 0x2c, 0x20, 0xb1, 0x45, 0x4c, 0x3c, 0xbe, 0x60, 0x75, 0x20, 0xa1, 0x80,
	0xa4, 0x24, 0x36, 0xb0, 0x72, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0a, 0xd8, 0xe2, 0x62,
	0xfc, 0x00, 0x00, 0x00,
}
