// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gomatcha.io/matcha/pb/view/android/pagerview.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class MatchaPagerViewPBPagerChildView;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - MatchaPagerViewPBPagerviewRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface MatchaPagerViewPBPagerviewRoot : GPBRootObject
@end

#pragma mark - MatchaPagerViewPBPagerChildView

typedef GPB_ENUM(MatchaPagerViewPBPagerChildView_FieldNumber) {
  MatchaPagerViewPBPagerChildView_FieldNumber_Title = 2,
};

@interface MatchaPagerViewPBPagerChildView : GPBMessage

/**
 * matcha.ImageOrResource icon = 3;
 * matcha.ImageOrResource selectedIcon = 4;
 * string badge = 5;
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *title;

@end

#pragma mark - MatchaPagerViewPBPagerView

typedef GPB_ENUM(MatchaPagerViewPBPagerView_FieldNumber) {
  MatchaPagerViewPBPagerView_FieldNumber_ChildViewsArray = 1,
  MatchaPagerViewPBPagerView_FieldNumber_SelectedIndex = 2,
};

@interface MatchaPagerViewPBPagerView : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<MatchaPagerViewPBPagerChildView*> *childViewsArray;
/** The number of items in @c childViewsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger childViewsArray_Count;

/**
 * matcha.Color barColor = 3;
 * matcha.Color selectedColor = 6;
 * matcha.Color unselectedColor = 7;
 * matcha.text.TextStyle selectedTextStyle = 8;
 * matcha.text.TextStyle unselectedTextStyle = 9;
 **/
@property(nonatomic, readwrite) int64_t selectedIndex;

@end

#pragma mark - MatchaPagerViewPBPagerEvent

typedef GPB_ENUM(MatchaPagerViewPBPagerEvent_FieldNumber) {
  MatchaPagerViewPBPagerEvent_FieldNumber_SelectedIndex = 1,
};

@interface MatchaPagerViewPBPagerEvent : GPBMessage

@property(nonatomic, readwrite) int64_t selectedIndex;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
