// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: github.com/gomatcha/matcha/proto/app/statusbar.proto

package com.github.gomatcha.matcha.proto.app;

public final class PbApp {
  private PbApp() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code app.StatusBarStyle}
   */
  public enum StatusBarStyle
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>STATUS_BAR_STYLE_DEFAULT = 0;</code>
     */
    STATUS_BAR_STYLE_DEFAULT(0),
    /**
     * <code>STATUS_BAR_STYLE_LIGHT = 1;</code>
     */
    STATUS_BAR_STYLE_LIGHT(1),
    /**
     * <code>STATUS_BAR_STYLE_DARK = 2;</code>
     */
    STATUS_BAR_STYLE_DARK(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>STATUS_BAR_STYLE_DEFAULT = 0;</code>
     */
    public static final int STATUS_BAR_STYLE_DEFAULT_VALUE = 0;
    /**
     * <code>STATUS_BAR_STYLE_LIGHT = 1;</code>
     */
    public static final int STATUS_BAR_STYLE_LIGHT_VALUE = 1;
    /**
     * <code>STATUS_BAR_STYLE_DARK = 2;</code>
     */
    public static final int STATUS_BAR_STYLE_DARK_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static StatusBarStyle valueOf(int value) {
      return forNumber(value);
    }

    public static StatusBarStyle forNumber(int value) {
      switch (value) {
        case 0: return STATUS_BAR_STYLE_DEFAULT;
        case 1: return STATUS_BAR_STYLE_LIGHT;
        case 2: return STATUS_BAR_STYLE_DARK;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<StatusBarStyle>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        StatusBarStyle> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<StatusBarStyle>() {
            public StatusBarStyle findValueByNumber(int number) {
              return StatusBarStyle.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.github.gomatcha.matcha.proto.app.PbApp.getDescriptor().getEnumTypes().get(0);
    }

    private static final StatusBarStyle[] VALUES = values();

    public static StatusBarStyle valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private StatusBarStyle(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:app.StatusBarStyle)
  }

  public interface ActivityIndicatorOrBuilder extends
      // @@protoc_insertion_point(interface_extends:app.ActivityIndicator)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool visible = 1;</code>
     */
    boolean getVisible();
  }
  /**
   * Protobuf type {@code app.ActivityIndicator}
   */
  public  static final class ActivityIndicator extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:app.ActivityIndicator)
      ActivityIndicatorOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ActivityIndicator.newBuilder() to construct.
    private ActivityIndicator(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ActivityIndicator() {
      visible_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ActivityIndicator(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              visible_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.gomatcha.matcha.proto.app.PbApp.internal_static_app_ActivityIndicator_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.gomatcha.matcha.proto.app.PbApp.internal_static_app_ActivityIndicator_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.gomatcha.matcha.proto.app.PbApp.ActivityIndicator.class, com.github.gomatcha.matcha.proto.app.PbApp.ActivityIndicator.Builder.class);
    }

    public static final int VISIBLE_FIELD_NUMBER = 1;
    private boolean visible_;
    /**
     * <code>bool visible = 1;</code>
     */
    public boolean getVisible() {
      return visible_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (visible_ != false) {
        output.writeBool(1, visible_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (visible_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, visible_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.gomatcha.matcha.proto.app.PbApp.ActivityIndicator)) {
        return super.equals(obj);
      }
      com.github.gomatcha.matcha.proto.app.PbApp.ActivityIndicator other = (com.github.gomatcha.matcha.proto.app.PbApp.ActivityIndicator) obj;

      boolean result = true;
      result = result && (getVisible()
          == other.getVisible());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VISIBLE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getVisible());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.gomatcha.matcha.proto.app.PbApp.ActivityIndicator parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.gomatcha.matcha.proto.app.PbApp.ActivityIndicator parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.gomatcha.matcha.proto.app.PbApp.ActivityIndicator parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.gomatcha.matcha.proto.app.PbApp.ActivityIndicator parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.gomatcha.matcha.proto.app.PbApp.ActivityIndicator parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.gomatcha.matcha.proto.app.PbApp.ActivityIndicator parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.gomatcha.matcha.proto.app.PbApp.ActivityIndicator parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.gomatcha.matcha.proto.app.PbApp.ActivityIndicator parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.gomatcha.matcha.proto.app.PbApp.ActivityIndicator parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.gomatcha.matcha.proto.app.PbApp.ActivityIndicator parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.gomatcha.matcha.proto.app.PbApp.ActivityIndicator parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.gomatcha.matcha.proto.app.PbApp.ActivityIndicator parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.gomatcha.matcha.proto.app.PbApp.ActivityIndicator prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code app.ActivityIndicator}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:app.ActivityIndicator)
        com.github.gomatcha.matcha.proto.app.PbApp.ActivityIndicatorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.gomatcha.matcha.proto.app.PbApp.internal_static_app_ActivityIndicator_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.gomatcha.matcha.proto.app.PbApp.internal_static_app_ActivityIndicator_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.gomatcha.matcha.proto.app.PbApp.ActivityIndicator.class, com.github.gomatcha.matcha.proto.app.PbApp.ActivityIndicator.Builder.class);
      }

      // Construct using com.github.gomatcha.matcha.proto.app.PbApp.ActivityIndicator.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        visible_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.gomatcha.matcha.proto.app.PbApp.internal_static_app_ActivityIndicator_descriptor;
      }

      @java.lang.Override
      public com.github.gomatcha.matcha.proto.app.PbApp.ActivityIndicator getDefaultInstanceForType() {
        return com.github.gomatcha.matcha.proto.app.PbApp.ActivityIndicator.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.gomatcha.matcha.proto.app.PbApp.ActivityIndicator build() {
        com.github.gomatcha.matcha.proto.app.PbApp.ActivityIndicator result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.gomatcha.matcha.proto.app.PbApp.ActivityIndicator buildPartial() {
        com.github.gomatcha.matcha.proto.app.PbApp.ActivityIndicator result = new com.github.gomatcha.matcha.proto.app.PbApp.ActivityIndicator(this);
        result.visible_ = visible_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.gomatcha.matcha.proto.app.PbApp.ActivityIndicator) {
          return mergeFrom((com.github.gomatcha.matcha.proto.app.PbApp.ActivityIndicator)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.gomatcha.matcha.proto.app.PbApp.ActivityIndicator other) {
        if (other == com.github.gomatcha.matcha.proto.app.PbApp.ActivityIndicator.getDefaultInstance()) return this;
        if (other.getVisible() != false) {
          setVisible(other.getVisible());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.gomatcha.matcha.proto.app.PbApp.ActivityIndicator parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.gomatcha.matcha.proto.app.PbApp.ActivityIndicator) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean visible_ ;
      /**
       * <code>bool visible = 1;</code>
       */
      public boolean getVisible() {
        return visible_;
      }
      /**
       * <code>bool visible = 1;</code>
       */
      public Builder setVisible(boolean value) {
        
        visible_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool visible = 1;</code>
       */
      public Builder clearVisible() {
        
        visible_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:app.ActivityIndicator)
    }

    // @@protoc_insertion_point(class_scope:app.ActivityIndicator)
    private static final com.github.gomatcha.matcha.proto.app.PbApp.ActivityIndicator DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.gomatcha.matcha.proto.app.PbApp.ActivityIndicator();
    }

    public static com.github.gomatcha.matcha.proto.app.PbApp.ActivityIndicator getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ActivityIndicator>
        PARSER = new com.google.protobuf.AbstractParser<ActivityIndicator>() {
      @java.lang.Override
      public ActivityIndicator parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ActivityIndicator(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ActivityIndicator> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ActivityIndicator> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.gomatcha.matcha.proto.app.PbApp.ActivityIndicator getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface StatusBarOrBuilder extends
      // @@protoc_insertion_point(interface_extends:app.StatusBar)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool hidden = 1;</code>
     */
    boolean getHidden();

    /**
     * <code>.app.StatusBarStyle style = 2;</code>
     */
    int getStyleValue();
    /**
     * <code>.app.StatusBarStyle style = 2;</code>
     */
    com.github.gomatcha.matcha.proto.app.PbApp.StatusBarStyle getStyle();
  }
  /**
   * Protobuf type {@code app.StatusBar}
   */
  public  static final class StatusBar extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:app.StatusBar)
      StatusBarOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use StatusBar.newBuilder() to construct.
    private StatusBar(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StatusBar() {
      hidden_ = false;
      style_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private StatusBar(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              hidden_ = input.readBool();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              style_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.gomatcha.matcha.proto.app.PbApp.internal_static_app_StatusBar_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.gomatcha.matcha.proto.app.PbApp.internal_static_app_StatusBar_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.gomatcha.matcha.proto.app.PbApp.StatusBar.class, com.github.gomatcha.matcha.proto.app.PbApp.StatusBar.Builder.class);
    }

    public static final int HIDDEN_FIELD_NUMBER = 1;
    private boolean hidden_;
    /**
     * <code>bool hidden = 1;</code>
     */
    public boolean getHidden() {
      return hidden_;
    }

    public static final int STYLE_FIELD_NUMBER = 2;
    private int style_;
    /**
     * <code>.app.StatusBarStyle style = 2;</code>
     */
    public int getStyleValue() {
      return style_;
    }
    /**
     * <code>.app.StatusBarStyle style = 2;</code>
     */
    public com.github.gomatcha.matcha.proto.app.PbApp.StatusBarStyle getStyle() {
      @SuppressWarnings("deprecation")
      com.github.gomatcha.matcha.proto.app.PbApp.StatusBarStyle result = com.github.gomatcha.matcha.proto.app.PbApp.StatusBarStyle.valueOf(style_);
      return result == null ? com.github.gomatcha.matcha.proto.app.PbApp.StatusBarStyle.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hidden_ != false) {
        output.writeBool(1, hidden_);
      }
      if (style_ != com.github.gomatcha.matcha.proto.app.PbApp.StatusBarStyle.STATUS_BAR_STYLE_DEFAULT.getNumber()) {
        output.writeEnum(2, style_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (hidden_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, hidden_);
      }
      if (style_ != com.github.gomatcha.matcha.proto.app.PbApp.StatusBarStyle.STATUS_BAR_STYLE_DEFAULT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, style_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.gomatcha.matcha.proto.app.PbApp.StatusBar)) {
        return super.equals(obj);
      }
      com.github.gomatcha.matcha.proto.app.PbApp.StatusBar other = (com.github.gomatcha.matcha.proto.app.PbApp.StatusBar) obj;

      boolean result = true;
      result = result && (getHidden()
          == other.getHidden());
      result = result && style_ == other.style_;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + HIDDEN_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getHidden());
      hash = (37 * hash) + STYLE_FIELD_NUMBER;
      hash = (53 * hash) + style_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.gomatcha.matcha.proto.app.PbApp.StatusBar parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.gomatcha.matcha.proto.app.PbApp.StatusBar parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.gomatcha.matcha.proto.app.PbApp.StatusBar parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.gomatcha.matcha.proto.app.PbApp.StatusBar parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.gomatcha.matcha.proto.app.PbApp.StatusBar parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.gomatcha.matcha.proto.app.PbApp.StatusBar parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.gomatcha.matcha.proto.app.PbApp.StatusBar parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.gomatcha.matcha.proto.app.PbApp.StatusBar parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.gomatcha.matcha.proto.app.PbApp.StatusBar parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.gomatcha.matcha.proto.app.PbApp.StatusBar parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.gomatcha.matcha.proto.app.PbApp.StatusBar parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.gomatcha.matcha.proto.app.PbApp.StatusBar parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.gomatcha.matcha.proto.app.PbApp.StatusBar prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code app.StatusBar}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:app.StatusBar)
        com.github.gomatcha.matcha.proto.app.PbApp.StatusBarOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.gomatcha.matcha.proto.app.PbApp.internal_static_app_StatusBar_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.gomatcha.matcha.proto.app.PbApp.internal_static_app_StatusBar_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.gomatcha.matcha.proto.app.PbApp.StatusBar.class, com.github.gomatcha.matcha.proto.app.PbApp.StatusBar.Builder.class);
      }

      // Construct using com.github.gomatcha.matcha.proto.app.PbApp.StatusBar.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        hidden_ = false;

        style_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.gomatcha.matcha.proto.app.PbApp.internal_static_app_StatusBar_descriptor;
      }

      @java.lang.Override
      public com.github.gomatcha.matcha.proto.app.PbApp.StatusBar getDefaultInstanceForType() {
        return com.github.gomatcha.matcha.proto.app.PbApp.StatusBar.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.gomatcha.matcha.proto.app.PbApp.StatusBar build() {
        com.github.gomatcha.matcha.proto.app.PbApp.StatusBar result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.gomatcha.matcha.proto.app.PbApp.StatusBar buildPartial() {
        com.github.gomatcha.matcha.proto.app.PbApp.StatusBar result = new com.github.gomatcha.matcha.proto.app.PbApp.StatusBar(this);
        result.hidden_ = hidden_;
        result.style_ = style_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.gomatcha.matcha.proto.app.PbApp.StatusBar) {
          return mergeFrom((com.github.gomatcha.matcha.proto.app.PbApp.StatusBar)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.gomatcha.matcha.proto.app.PbApp.StatusBar other) {
        if (other == com.github.gomatcha.matcha.proto.app.PbApp.StatusBar.getDefaultInstance()) return this;
        if (other.getHidden() != false) {
          setHidden(other.getHidden());
        }
        if (other.style_ != 0) {
          setStyleValue(other.getStyleValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.gomatcha.matcha.proto.app.PbApp.StatusBar parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.gomatcha.matcha.proto.app.PbApp.StatusBar) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean hidden_ ;
      /**
       * <code>bool hidden = 1;</code>
       */
      public boolean getHidden() {
        return hidden_;
      }
      /**
       * <code>bool hidden = 1;</code>
       */
      public Builder setHidden(boolean value) {
        
        hidden_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool hidden = 1;</code>
       */
      public Builder clearHidden() {
        
        hidden_ = false;
        onChanged();
        return this;
      }

      private int style_ = 0;
      /**
       * <code>.app.StatusBarStyle style = 2;</code>
       */
      public int getStyleValue() {
        return style_;
      }
      /**
       * <code>.app.StatusBarStyle style = 2;</code>
       */
      public Builder setStyleValue(int value) {
        style_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.app.StatusBarStyle style = 2;</code>
       */
      public com.github.gomatcha.matcha.proto.app.PbApp.StatusBarStyle getStyle() {
        @SuppressWarnings("deprecation")
        com.github.gomatcha.matcha.proto.app.PbApp.StatusBarStyle result = com.github.gomatcha.matcha.proto.app.PbApp.StatusBarStyle.valueOf(style_);
        return result == null ? com.github.gomatcha.matcha.proto.app.PbApp.StatusBarStyle.UNRECOGNIZED : result;
      }
      /**
       * <code>.app.StatusBarStyle style = 2;</code>
       */
      public Builder setStyle(com.github.gomatcha.matcha.proto.app.PbApp.StatusBarStyle value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        style_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.app.StatusBarStyle style = 2;</code>
       */
      public Builder clearStyle() {
        
        style_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:app.StatusBar)
    }

    // @@protoc_insertion_point(class_scope:app.StatusBar)
    private static final com.github.gomatcha.matcha.proto.app.PbApp.StatusBar DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.gomatcha.matcha.proto.app.PbApp.StatusBar();
    }

    public static com.github.gomatcha.matcha.proto.app.PbApp.StatusBar getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StatusBar>
        PARSER = new com.google.protobuf.AbstractParser<StatusBar>() {
      @java.lang.Override
      public StatusBar parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StatusBar(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<StatusBar> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StatusBar> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.gomatcha.matcha.proto.app.PbApp.StatusBar getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_app_ActivityIndicator_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_app_ActivityIndicator_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_app_StatusBar_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_app_StatusBar_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n4github.com/gomatcha/matcha/proto/app/s" +
      "tatusbar.proto\022\003app\"$\n\021ActivityIndicator" +
      "\022\017\n\007visible\030\001 \001(\010\"?\n\tStatusBar\022\016\n\006hidden" +
      "\030\001 \001(\010\022\"\n\005style\030\002 \001(\0162\023.app.StatusBarSty" +
      "le*e\n\016StatusBarStyle\022\034\n\030STATUS_BAR_STYLE" +
      "_DEFAULT\020\000\022\032\n\026STATUS_BAR_STYLE_LIGHT\020\001\022\031" +
      "\n\025STATUS_BAR_STYLE_DARK\020\002B@\n$com.github." +
      "gomatcha.matcha.proto.appB\005PbAppZ\003app\242\002\013" +
      "MatchaAppPBb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_app_ActivityIndicator_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_app_ActivityIndicator_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_app_ActivityIndicator_descriptor,
        new java.lang.String[] { "Visible", });
    internal_static_app_StatusBar_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_app_StatusBar_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_app_StatusBar_descriptor,
        new java.lang.String[] { "Hidden", "Style", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
