// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/gomatcha/matcha/proto/view/ios/segmentview.proto

package ios

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SegmentView struct {
	Value                int64    `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Titles               []string `protobuf:"bytes,2,rep,name=titles,proto3" json:"titles,omitempty"`
	Momentary            bool     `protobuf:"varint,3,opt,name=momentary,proto3" json:"momentary,omitempty"`
	Enabled              bool     `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SegmentView) Reset()         { *m = SegmentView{} }
func (m *SegmentView) String() string { return proto.CompactTextString(m) }
func (*SegmentView) ProtoMessage()    {}
func (*SegmentView) Descriptor() ([]byte, []int) {
	return fileDescriptor_49f5166f1af7eddf, []int{0}
}
func (m *SegmentView) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SegmentView.Unmarshal(m, b)
}
func (m *SegmentView) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SegmentView.Marshal(b, m, deterministic)
}
func (m *SegmentView) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SegmentView.Merge(m, src)
}
func (m *SegmentView) XXX_Size() int {
	return xxx_messageInfo_SegmentView.Size(m)
}
func (m *SegmentView) XXX_DiscardUnknown() {
	xxx_messageInfo_SegmentView.DiscardUnknown(m)
}

var xxx_messageInfo_SegmentView proto.InternalMessageInfo

func (m *SegmentView) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *SegmentView) GetTitles() []string {
	if m != nil {
		return m.Titles
	}
	return nil
}

func (m *SegmentView) GetMomentary() bool {
	if m != nil {
		return m.Momentary
	}
	return false
}

func (m *SegmentView) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

type SegmentViewEvent struct {
	Value                int64    `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SegmentViewEvent) Reset()         { *m = SegmentViewEvent{} }
func (m *SegmentViewEvent) String() string { return proto.CompactTextString(m) }
func (*SegmentViewEvent) ProtoMessage()    {}
func (*SegmentViewEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_49f5166f1af7eddf, []int{1}
}
func (m *SegmentViewEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SegmentViewEvent.Unmarshal(m, b)
}
func (m *SegmentViewEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SegmentViewEvent.Marshal(b, m, deterministic)
}
func (m *SegmentViewEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SegmentViewEvent.Merge(m, src)
}
func (m *SegmentViewEvent) XXX_Size() int {
	return xxx_messageInfo_SegmentViewEvent.Size(m)
}
func (m *SegmentViewEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_SegmentViewEvent.DiscardUnknown(m)
}

var xxx_messageInfo_SegmentViewEvent proto.InternalMessageInfo

func (m *SegmentViewEvent) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func init() {
	proto.RegisterType((*SegmentView)(nil), "matcha.view.ios.SegmentView")
	proto.RegisterType((*SegmentViewEvent)(nil), "matcha.view.ios.SegmentViewEvent")
}

func init() {
	proto.RegisterFile("github.com/gomatcha/matcha/proto/view/ios/segmentview.proto", fileDescriptor_49f5166f1af7eddf)
}

var fileDescriptor_49f5166f1af7eddf = []byte{
	// 229 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xb2, 0x4e, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0x4f, 0xcf, 0xcf, 0x4d, 0x2c, 0x49, 0xce, 0x48, 0xd4,
	0x87, 0x52, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0xfa, 0x65, 0x99, 0xa9, 0xe5, 0xfa, 0x99, 0xf9, 0xc5,
	0xfa, 0xc5, 0xa9, 0xe9, 0xb9, 0xa9, 0x79, 0x25, 0x20, 0xbe, 0x1e, 0x58, 0x4a, 0x88, 0x1f, 0xa2,
	0x50, 0x0f, 0x2c, 0x94, 0x99, 0x5f, 0xac, 0x54, 0xcc, 0xc5, 0x1d, 0x0c, 0x51, 0x15, 0x96, 0x99,
	0x5a, 0x2e, 0x24, 0xc2, 0xc5, 0x5a, 0x96, 0x98, 0x53, 0x9a, 0x2a, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1,
	0x1c, 0x04, 0xe1, 0x08, 0x89, 0x71, 0xb1, 0x95, 0x64, 0x96, 0xe4, 0xa4, 0x16, 0x4b, 0x30, 0x29,
	0x30, 0x6b, 0x70, 0x06, 0x41, 0x79, 0x42, 0x32, 0x5c, 0x9c, 0xb9, 0xf9, 0x20, 0xbd, 0x89, 0x45,
	0x95, 0x12, 0xcc, 0x0a, 0x8c, 0x1a, 0x1c, 0x41, 0x08, 0x01, 0x21, 0x09, 0x2e, 0xf6, 0xd4, 0xbc,
	0xc4, 0xa4, 0x9c, 0xd4, 0x14, 0x09, 0x16, 0xb0, 0x1c, 0x8c, 0xab, 0xa4, 0xc1, 0x25, 0x80, 0x64,
	0xa9, 0x6b, 0x59, 0x6a, 0x5e, 0x09, 0x76, 0x9b, 0x9d, 0x7c, 0xb9, 0x34, 0x93, 0xf3, 0x73, 0xf5,
	0xa0, 0x5e, 0x86, 0x79, 0x57, 0x0f, 0x4a, 0x81, 0xfd, 0x04, 0xf7, 0x8b, 0x13, 0x6f, 0x40, 0x12,
	0x92, 0xb1, 0x51, 0xcc, 0x99, 0xf9, 0xc5, 0x8b, 0x98, 0xb8, 0x7d, 0xc1, 0x6a, 0x33, 0xfd, 0x83,
	0x03, 0x9c, 0x92, 0xd8, 0xc0, 0x3a, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe1, 0x3e, 0xa7,
	0x55, 0x44, 0x01, 0x00, 0x00,
}
