// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gomatcha.io/matcha/pb/env/resource.proto

/*
Package env is a generated protocol buffer package.

It is generated from these files:
	gomatcha.io/matcha/pb/env/resource.proto

It has these top-level messages:
	Resource
	ImageResource
*/
package env

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Resource struct {
	Path string `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
}

func (m *Resource) Reset()                    { *m = Resource{} }
func (m *Resource) String() string            { return proto.CompactTextString(m) }
func (*Resource) ProtoMessage()               {}
func (*Resource) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Resource) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type ImageResource struct {
	Path string `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
}

func (m *ImageResource) Reset()                    { *m = ImageResource{} }
func (m *ImageResource) String() string            { return proto.CompactTextString(m) }
func (*ImageResource) ProtoMessage()               {}
func (*ImageResource) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ImageResource) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func init() {
	proto.RegisterType((*Resource)(nil), "env.Resource")
	proto.RegisterType((*ImageResource)(nil), "env.ImageResource")
}

func init() { proto.RegisterFile("gomatcha.io/matcha/pb/env/resource.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 145 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x48, 0xcf, 0xcf, 0x4d,
	0x2c, 0x49, 0xce, 0x48, 0xd4, 0xcb, 0xcc, 0xd7, 0x87, 0xb0, 0xf4, 0x0b, 0x92, 0xf4, 0x53, 0xf3,
	0xca, 0xf4, 0x8b, 0x52, 0x8b, 0xf3, 0x4b, 0x8b, 0x92, 0x53, 0xf5, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2,
	0x85, 0x98, 0x53, 0xf3, 0xca, 0x94, 0xe4, 0xb8, 0x38, 0x82, 0xa0, 0xc2, 0x42, 0x42, 0x5c, 0x2c,
	0x05, 0x89, 0x25, 0x19, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0xb6, 0x92, 0x32, 0x17,
	0xaf, 0x67, 0x6e, 0x62, 0x7a, 0x2a, 0x3e, 0x45, 0x4e, 0xa6, 0x5c, 0x92, 0x99, 0xf9, 0x7a, 0x70,
	0x8b, 0xa1, 0x54, 0x41, 0x92, 0x5e, 0x6a, 0x5e, 0x99, 0x13, 0x6b, 0x40, 0x92, 0x6b, 0x5e, 0x59,
	0x14, 0xc8, 0xb6, 0x45, 0x4c, 0xdc, 0xbe, 0x60, 0xb9, 0x00, 0x27, 0xd7, 0xbc, 0xb2, 0x24, 0x36,
	0xb0, 0x3b, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xd2, 0xa9, 0xa4, 0x49, 0xb3, 0x00, 0x00,
	0x00,
}
