package proto

//go:generate bash -c "( cd $GOPATH/src && protoc --go_out=. gomatcha.io/matcha/proto/*.proto )"
//go:generate bash -c "( cd $GOPATH/src && protoc --go_out=. gomatcha.io/matcha/proto/app/*.proto )"
//go:generate bash -c "( cd $GOPATH/src && protoc --go_out=. gomatcha.io/matcha/proto/env/*.proto )"
//go:generate bash -c "( cd $GOPATH/src && protoc --go_out=. gomatcha.io/matcha/proto/keyboard/*.proto )"
//go:generate bash -c "( cd $GOPATH/src && protoc --go_out=. gomatcha.io/matcha/proto/layout/*.proto )"
//go:generate bash -c "( cd $GOPATH/src && protoc --go_out=. gomatcha.io/matcha/proto/paint/*.proto )"
//go:generate bash -c "( cd $GOPATH/src && protoc --go_out=. gomatcha.io/matcha/proto/text/*.proto )"
//go:generate bash -c "( cd $GOPATH/src && protoc --go_out=. gomatcha.io/matcha/proto/touch/*.proto )"
//go:generate bash -c "( cd $GOPATH/src && protoc --go_out=. gomatcha.io/matcha/proto/view/*.proto )"
//go:generate bash -c "( cd $GOPATH/src && protoc --go_out=. gomatcha.io/matcha/proto/view/android/*.proto )"
//go:generate bash -c "( cd $GOPATH/src && protoc --go_out=. gomatcha.io/matcha/proto/view/ios/*.proto )"

//go:generate bash -c "( cd $GOPATH/src && protoc --java_out=gomatcha.io/matcha/android/MatchaLib/matcha/src/main/java gomatcha.io/matcha/proto/*.proto )"
//go:generate bash -c "( cd $GOPATH/src && protoc --java_out=gomatcha.io/matcha/android/MatchaLib/matcha/src/main/java gomatcha.io/matcha/proto/app/*.proto )"
//go:generate bash -c "( cd $GOPATH/src && protoc --java_out=gomatcha.io/matcha/android/MatchaLib/matcha/src/main/java gomatcha.io/matcha/proto/env/*.proto )"
//go:generate bash -c "( cd $GOPATH/src && protoc --java_out=gomatcha.io/matcha/android/MatchaLib/matcha/src/main/java gomatcha.io/matcha/proto/keyboard/*.proto )"
//go:generate bash -c "( cd $GOPATH/src && protoc --java_out=gomatcha.io/matcha/android/MatchaLib/matcha/src/main/java gomatcha.io/matcha/proto/layout/*.proto )"
//go:generate bash -c "( cd $GOPATH/src && protoc --java_out=gomatcha.io/matcha/android/MatchaLib/matcha/src/main/java gomatcha.io/matcha/proto/paint/*.proto )"
//go:generate bash -c "( cd $GOPATH/src && protoc --java_out=gomatcha.io/matcha/android/MatchaLib/matcha/src/main/java gomatcha.io/matcha/proto/text/*.proto )"
//go:generate bash -c "( cd $GOPATH/src && protoc --java_out=gomatcha.io/matcha/android/MatchaLib/matcha/src/main/java gomatcha.io/matcha/proto/touch/*.proto )"
//go:generate bash -c "( cd $GOPATH/src && protoc --java_out=gomatcha.io/matcha/android/MatchaLib/matcha/src/main/java gomatcha.io/matcha/proto/view/*.proto )"
//go:generate bash -c "( cd $GOPATH/src && protoc --java_out=gomatcha.io/matcha/android/MatchaLib/matcha/src/main/java gomatcha.io/matcha/proto/view/android/*.proto )"

//go:generate bash -c "( cd $GOPATH/src && protoc --objc_out=gomatcha.io/matcha/ios/Matcha/Protobuf gomatcha.io/matcha/proto/*.proto )"
//go:generate bash -c "( cd $GOPATH/src && protoc --objc_out=gomatcha.io/matcha/ios/Matcha/Protobuf gomatcha.io/matcha/proto/app/*.proto )"
//go:generate bash -c "( cd $GOPATH/src && protoc --objc_out=gomatcha.io/matcha/ios/Matcha/Protobuf gomatcha.io/matcha/proto/env/*.proto )"
//go:generate bash -c "( cd $GOPATH/src && protoc --objc_out=gomatcha.io/matcha/ios/Matcha/Protobuf gomatcha.io/matcha/proto/keyboard/*.proto )"
//go:generate bash -c "( cd $GOPATH/src && protoc --objc_out=gomatcha.io/matcha/ios/Matcha/Protobuf gomatcha.io/matcha/proto/layout/*.proto )"
//go:generate bash -c "( cd $GOPATH/src && protoc --objc_out=gomatcha.io/matcha/ios/Matcha/Protobuf gomatcha.io/matcha/proto/paint/*.proto )"
//go:generate bash -c "( cd $GOPATH/src && protoc --objc_out=gomatcha.io/matcha/ios/Matcha/Protobuf gomatcha.io/matcha/proto/text/*.proto )"
//go:generate bash -c "( cd $GOPATH/src && protoc --objc_out=gomatcha.io/matcha/ios/Matcha/Protobuf gomatcha.io/matcha/proto/touch/*.proto )"
//go:generate bash -c "( cd $GOPATH/src && protoc --objc_out=gomatcha.io/matcha/ios/Matcha/Protobuf gomatcha.io/matcha/proto/view/*.proto )"
//go:generate bash -c "( cd $GOPATH/src && protoc --objc_out=gomatcha.io/matcha/ios/Matcha/Protobuf gomatcha.io/matcha/proto/view/ios/*.proto )"
