package proto

//go:generate bash -c "( cd $GOPATH/src && protoc --go_out=. github.com/gomatcha/matcha/proto/*.proto )"
//go:generate bash -c "( cd $GOPATH/src && protoc --go_out=. github.com/gomatcha/matcha/proto/app/*.proto )"
//go:generate bash -c "( cd $GOPATH/src && protoc --go_out=. github.com/gomatcha/matcha/proto/env/*.proto )"
//go:generate bash -c "( cd $GOPATH/src && protoc --go_out=. github.com/gomatcha/matcha/proto/keyboard/*.proto )"
//go:generate bash -c "( cd $GOPATH/src && protoc --go_out=. github.com/gomatcha/matcha/proto/layout/*.proto )"
//go:generate bash -c "( cd $GOPATH/src && protoc --go_out=. github.com/gomatcha/matcha/proto/paint/*.proto )"
//go:generate bash -c "( cd $GOPATH/src && protoc --go_out=. github.com/gomatcha/matcha/proto/text/*.proto )"
//go:generate bash -c "( cd $GOPATH/src && protoc --go_out=. github.com/gomatcha/matcha/proto/pointer/*.proto )"
//go:generate bash -c "( cd $GOPATH/src && protoc --go_out=. github.com/gomatcha/matcha/proto/view/*.proto )"
//go:generate bash -c "( cd $GOPATH/src && protoc --go_out=. github.com/gomatcha/matcha/proto/view/android/*.proto )"
//go:generate bash -c "( cd $GOPATH/src && protoc --go_out=. github.com/gomatcha/matcha/proto/view/ios/*.proto )"

//go:generate bash -c "( cd $GOPATH/src && protoc --java_out=github.com/gomatcha/matcha/android/MatchaLib/matcha/src/main/java github.com/gomatcha/matcha/proto/*.proto )"
//go:generate bash -c "( cd $GOPATH/src && protoc --java_out=github.com/gomatcha/matcha/android/MatchaLib/matcha/src/main/java github.com/gomatcha/matcha/proto/app/*.proto )"
//go:generate bash -c "( cd $GOPATH/src && protoc --java_out=github.com/gomatcha/matcha/android/MatchaLib/matcha/src/main/java github.com/gomatcha/matcha/proto/env/*.proto )"
//go:generate bash -c "( cd $GOPATH/src && protoc --java_out=github.com/gomatcha/matcha/android/MatchaLib/matcha/src/main/java github.com/gomatcha/matcha/proto/keyboard/*.proto )"
//go:generate bash -c "( cd $GOPATH/src && protoc --java_out=github.com/gomatcha/matcha/android/MatchaLib/matcha/src/main/java github.com/gomatcha/matcha/proto/layout/*.proto )"
//go:generate bash -c "( cd $GOPATH/src && protoc --java_out=github.com/gomatcha/matcha/android/MatchaLib/matcha/src/main/java github.com/gomatcha/matcha/proto/paint/*.proto )"
//go:generate bash -c "( cd $GOPATH/src && protoc --java_out=github.com/gomatcha/matcha/android/MatchaLib/matcha/src/main/java github.com/gomatcha/matcha/proto/text/*.proto )"
//go:generate bash -c "( cd $GOPATH/src && protoc --java_out=github.com/gomatcha/matcha/android/MatchaLib/matcha/src/main/java github.com/gomatcha/matcha/proto/pointer/*.proto )"
//go:generate bash -c "( cd $GOPATH/src && protoc --java_out=github.com/gomatcha/matcha/android/MatchaLib/matcha/src/main/java github.com/gomatcha/matcha/proto/view/*.proto )"
//go:generate bash -c "( cd $GOPATH/src && protoc --java_out=github.com/gomatcha/matcha/android/MatchaLib/matcha/src/main/java github.com/gomatcha/matcha/proto/view/android/*.proto )"

//go:generate bash -c "( cd $GOPATH/src && protoc --objc_out=github.com/gomatcha/matcha/ios/Matcha/Protobuf github.com/gomatcha/matcha/proto/*.proto )"
//go:generate bash -c "( cd $GOPATH/src && protoc --objc_out=github.com/gomatcha/matcha/ios/Matcha/Protobuf github.com/gomatcha/matcha/proto/app/*.proto )"
//go:generate bash -c "( cd $GOPATH/src && protoc --objc_out=github.com/gomatcha/matcha/ios/Matcha/Protobuf github.com/gomatcha/matcha/proto/env/*.proto )"
//go:generate bash -c "( cd $GOPATH/src && protoc --objc_out=github.com/gomatcha/matcha/ios/Matcha/Protobuf github.com/gomatcha/matcha/proto/keyboard/*.proto )"
//go:generate bash -c "( cd $GOPATH/src && protoc --objc_out=github.com/gomatcha/matcha/ios/Matcha/Protobuf github.com/gomatcha/matcha/proto/layout/*.proto )"
//go:generate bash -c "( cd $GOPATH/src && protoc --objc_out=github.com/gomatcha/matcha/ios/Matcha/Protobuf github.com/gomatcha/matcha/proto/paint/*.proto )"
//go:generate bash -c "( cd $GOPATH/src && protoc --objc_out=github.com/gomatcha/matcha/ios/Matcha/Protobuf github.com/gomatcha/matcha/proto/text/*.proto )"
//go:generate bash -c "( cd $GOPATH/src && protoc --objc_out=github.com/gomatcha/matcha/ios/Matcha/Protobuf github.com/gomatcha/matcha/proto/pointer/*.proto )"
//go:generate bash -c "( cd $GOPATH/src && protoc --objc_out=github.com/gomatcha/matcha/ios/Matcha/Protobuf github.com/gomatcha/matcha/proto/view/*.proto )"
//go:generate bash -c "( cd $GOPATH/src && protoc --objc_out=github.com/gomatcha/matcha/ios/Matcha/Protobuf github.com/gomatcha/matcha/proto/view/ios/*.proto )"
