// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gomatcha.io/matcha/pb/color.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	gomatcha.io/matcha/pb/color.proto
	gomatcha.io/matcha/pb/image.proto

It has these top-level messages:
	Color
	Image
	ImageProperties
	ImageOrResource
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Color struct {
	Red   uint32 `protobuf:"varint,1,opt,name=red" json:"red,omitempty"`
	Blue  uint32 `protobuf:"varint,2,opt,name=blue" json:"blue,omitempty"`
	Green uint32 `protobuf:"varint,3,opt,name=green" json:"green,omitempty"`
	Alpha uint32 `protobuf:"varint,4,opt,name=alpha" json:"alpha,omitempty"`
}

func (m *Color) Reset()                    { *m = Color{} }
func (m *Color) String() string            { return proto.CompactTextString(m) }
func (*Color) ProtoMessage()               {}
func (*Color) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Color) GetRed() uint32 {
	if m != nil {
		return m.Red
	}
	return 0
}

func (m *Color) GetBlue() uint32 {
	if m != nil {
		return m.Blue
	}
	return 0
}

func (m *Color) GetGreen() uint32 {
	if m != nil {
		return m.Green
	}
	return 0
}

func (m *Color) GetAlpha() uint32 {
	if m != nil {
		return m.Alpha
	}
	return 0
}

func init() {
	proto.RegisterType((*Color)(nil), "matcha.Color")
}

func init() { proto.RegisterFile("gomatcha.io/matcha/pb/color.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 141 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x4c, 0xcf, 0xcf, 0x4d,
	0x2c, 0x49, 0xce, 0x48, 0xd4, 0xcb, 0xcc, 0xd7, 0x87, 0xb0, 0xf4, 0x0b, 0x92, 0xf4, 0x93, 0xf3,
	0x73, 0xf2, 0x8b, 0xf4, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0xd8, 0x20, 0xc2, 0x4a, 0x91, 0x5c,
	0xac, 0xce, 0x20, 0x61, 0x21, 0x01, 0x2e, 0xe6, 0xa2, 0xd4, 0x14, 0x09, 0x46, 0x05, 0x46, 0x0d,
	0xde, 0x20, 0x10, 0x53, 0x48, 0x88, 0x8b, 0x25, 0x29, 0xa7, 0x34, 0x55, 0x82, 0x09, 0x2c, 0x04,
	0x66, 0x0b, 0x89, 0x70, 0xb1, 0xa6, 0x17, 0xa5, 0xa6, 0xe6, 0x49, 0x30, 0x83, 0x05, 0x21, 0x1c,
	0x90, 0x68, 0x62, 0x4e, 0x41, 0x46, 0xa2, 0x04, 0x0b, 0x44, 0x14, 0xcc, 0x71, 0xe2, 0x8f, 0x62,
	0x2a, 0x48, 0x5a, 0xc4, 0xc4, 0xe1, 0x0b, 0xb6, 0x29, 0xc0, 0x29, 0x89, 0x0d, 0x6c, 0xb5, 0x31,
	0x20, 0x00, 0x00, 0xff, 0xff, 0x99, 0x79, 0x5c, 0x3b, 0x9f, 0x00, 0x00, 0x00,
}
